<map version="freeplane 1.11.1">
<!--To view this file, download free mind mapping software Freeplane from https://www.freeplane.org -->
<node TEXT="РАЗРАБОТКА БЕЗОПАСНОГО ПРОГРАММНОГО ОБЕСПЕЧЕНИЯ&#xa;Общие требования" LOCALIZED_STYLE_REF="AutomaticLayout.level.root" FOLDED="false" ID="ID_1090958577" CREATED="1409300609620" MODIFIED="1685112122933" ICON_SIZE="12 pt" COLOR="#ffffff" BACKGROUND_COLOR="#0066cc" STYLE="bubble" SHAPE_HORIZONTAL_MARGIN="20 px" SHAPE_VERTICAL_MARGIN="20 px" NUMBERED="false" FORMAT="STANDARD_FORMAT" TEXT_ALIGN="CENTER" MAX_WIDTH="10 cm" MIN_WIDTH="0 cm" BORDER_WIDTH_LIKE_EDGE="false" BORDER_WIDTH="3.1 px" BORDER_COLOR_LIKE_EDGE="true" BORDER_COLOR="#2c2b29" BORDER_DASH_LIKE_EDGE="true" BORDER_DASH="SOLID" VGAP_QUANTITY="3 pt" SHAPE_HORIZONTAL_MARGIN_QUANTITY="10 pt" SHAPE_VERTICAL_MARGIN_QUANTITY="10 pt">
<font NAME="SansSerif" SIZE="18" BOLD="true" STRIKETHROUGH="false" ITALIC="false"/>
<edge STYLE="bezier" COLOR="#93a1a1" WIDTH="3" DASH="SOLID"/>
<hook NAME="accessories/plugins/AutomaticLayout.properties" VALUE="ALL"/>
<hook NAME="MapStyle" background="#fdf6e3" zoom="0.378">
    <properties show_icon_for_attributes="true" edgeColorConfiguration="#808080ff,#ff0000ff,#0000ffff,#00ff00ff,#ff00ffff,#00ffffff,#7c0000ff,#00007cff,#007c00ff,#7c007cff,#007c7cff,#7c7c00ff" show_note_icons="true" associatedTemplateLocation="template:/light_solarized_template.mm" fit_to_viewport="false"/>

<map_styles>
<stylenode LOCALIZED_TEXT="styles.root_node" STYLE="oval" UNIFORM_SHAPE="true" VGAP_QUANTITY="24 pt">
<font SIZE="24"/>
<stylenode LOCALIZED_TEXT="styles.predefined" POSITION="bottom_or_right" STYLE="bubble">
<stylenode LOCALIZED_TEXT="default" ID="ID_271890427" ICON_SIZE="12 pt" COLOR="#000000" STYLE="fork">
<arrowlink SHAPE="CUBIC_CURVE" COLOR="#000000" WIDTH="2" TRANSPARENCY="200" DASH="" FONT_SIZE="9" FONT_FAMILY="SansSerif" DESTINATION="ID_271890427" STARTARROW="NONE" ENDARROW="DEFAULT"/>
<font NAME="SansSerif" SIZE="10" BOLD="false" ITALIC="false"/>
<richcontent CONTENT-TYPE="plain/auto" TYPE="DETAILS"/>
<richcontent TYPE="NOTE" CONTENT-TYPE="plain/auto"/>
</stylenode>
<stylenode LOCALIZED_TEXT="defaultstyle.details"/>
<stylenode LOCALIZED_TEXT="defaultstyle.attributes">
<font SIZE="9"/>
</stylenode>
<stylenode LOCALIZED_TEXT="defaultstyle.note" COLOR="#000000" BACKGROUND_COLOR="#ffffff" TEXT_ALIGN="LEFT"/>
<stylenode LOCALIZED_TEXT="defaultstyle.floating">
<edge STYLE="hide_edge"/>
<cloud COLOR="#f0f0f0" SHAPE="ROUND_RECT"/>
</stylenode>
<stylenode LOCALIZED_TEXT="defaultstyle.selection" BACKGROUND_COLOR="#afd3f7" BORDER_COLOR_LIKE_EDGE="false" BORDER_COLOR="#afd3f7"/>
</stylenode>
<stylenode LOCALIZED_TEXT="styles.user-defined" POSITION="bottom_or_right" STYLE="bubble">
<stylenode LOCALIZED_TEXT="styles.topic" COLOR="#18898b" STYLE="fork">
<font NAME="Liberation Sans" SIZE="10" BOLD="true"/>
</stylenode>
<stylenode LOCALIZED_TEXT="styles.subtopic" COLOR="#cc3300" STYLE="fork">
<font NAME="Liberation Sans" SIZE="10" BOLD="true"/>
</stylenode>
<stylenode LOCALIZED_TEXT="styles.subsubtopic" COLOR="#669900">
<font NAME="Liberation Sans" SIZE="10" BOLD="true"/>
</stylenode>
<stylenode LOCALIZED_TEXT="styles.important" ID="ID_67550811">
<icon BUILTIN="yes"/>
<arrowlink COLOR="#003399" TRANSPARENCY="255" DESTINATION="ID_67550811"/>
</stylenode>
</stylenode>
<stylenode LOCALIZED_TEXT="styles.AutomaticLayout" POSITION="bottom_or_right" STYLE="bubble">
<stylenode LOCALIZED_TEXT="AutomaticLayout.level.root" COLOR="#000000" STYLE="oval" SHAPE_HORIZONTAL_MARGIN="10 pt" SHAPE_VERTICAL_MARGIN="10 pt">
<font SIZE="18"/>
</stylenode>
<stylenode LOCALIZED_TEXT="AutomaticLayout.level,1" COLOR="#0033ff">
<font SIZE="16"/>
</stylenode>
<stylenode LOCALIZED_TEXT="AutomaticLayout.level,2" COLOR="#00b439">
<font SIZE="14"/>
</stylenode>
<stylenode LOCALIZED_TEXT="AutomaticLayout.level,3" COLOR="#990000">
<font SIZE="12"/>
</stylenode>
<stylenode LOCALIZED_TEXT="AutomaticLayout.level,4" COLOR="#111111">
<font SIZE="10"/>
</stylenode>
<stylenode LOCALIZED_TEXT="AutomaticLayout.level,5"/>
<stylenode LOCALIZED_TEXT="AutomaticLayout.level,6"/>
<stylenode LOCALIZED_TEXT="AutomaticLayout.level,7"/>
<stylenode LOCALIZED_TEXT="AutomaticLayout.level,8"/>
<stylenode LOCALIZED_TEXT="AutomaticLayout.level,9"/>
<stylenode LOCALIZED_TEXT="AutomaticLayout.level,10"/>
<stylenode LOCALIZED_TEXT="AutomaticLayout.level,11"/>
</stylenode>
</stylenode>
</map_styles>
</hook>
<node TEXT="Область применения" POSITION="bottom_or_right" ID="ID_1447779137" CREATED="1684937145558" MODIFIED="1685113001183" ICON_SIZE="12 pt" COLOR="#ffffff" BACKGROUND_COLOR="#0033cc" STYLE="bubble" SHAPE_HORIZONTAL_MARGIN="16 px" SHAPE_VERTICAL_MARGIN="10 px" NUMBERED="false" FORMAT="STANDARD_FORMAT" TEXT_ALIGN="CENTER" MAX_WIDTH="10 cm" MIN_WIDTH="0 cm" BORDER_WIDTH_LIKE_EDGE="false" BORDER_WIDTH="1.9 px" BORDER_COLOR_LIKE_EDGE="true" BORDER_COLOR="#2c2b29" BORDER_DASH_LIKE_EDGE="true" BORDER_DASH="SOLID" HGAP_QUANTITY="-465.75 pt" VSHIFT_QUANTITY="2139.49998 pt" SHAPE_HORIZONTAL_MARGIN_QUANTITY="8 pt" SHAPE_VERTICAL_MARGIN_QUANTITY="5 pt">
<font NAME="SansSerif" SIZE="16" BOLD="false" STRIKETHROUGH="false" ITALIC="false"/>
<edge STYLE="bezier" COLOR="#93a1a1" WIDTH="3" DASH="SOLID"/>
</node>
<node TEXT="Нормативные ссылки" POSITION="bottom_or_right" ID="ID_1050236059" CREATED="1684937223200" MODIFIED="1685113151882" ICON_SIZE="12 pt" COLOR="#ffffff" BACKGROUND_COLOR="#0033cc" STYLE="bubble" SHAPE_HORIZONTAL_MARGIN="16 px" SHAPE_VERTICAL_MARGIN="10 px" NUMBERED="false" FORMAT="STANDARD_FORMAT" TEXT_ALIGN="CENTER" MAX_WIDTH="10 cm" MIN_WIDTH="0 cm" BORDER_WIDTH_LIKE_EDGE="false" BORDER_WIDTH="1.9 px" BORDER_COLOR_LIKE_EDGE="true" BORDER_COLOR="#2c2b29" BORDER_DASH_LIKE_EDGE="true" BORDER_DASH="SOLID" HGAP_QUANTITY="-180.99999 pt" VSHIFT_QUANTITY="14.74999 pt" SHAPE_HORIZONTAL_MARGIN_QUANTITY="8 pt" SHAPE_VERTICAL_MARGIN_QUANTITY="5 pt">
<font NAME="SansSerif" SIZE="16" BOLD="false" STRIKETHROUGH="false" ITALIC="false"/>
<edge STYLE="bezier" COLOR="#93a1a1" WIDTH="3" DASH="SOLID"/>
<node TEXT="ГОСТ 2.001 Единая система конструкторской документации." ID="ID_449725850" CREATED="1684939514794" MODIFIED="1685112119237" ICON_SIZE="12 pt" COLOR="#ffffff" BACKGROUND_COLOR="#0066cc" STYLE="bubble" SHAPE_HORIZONTAL_MARGIN="16 px" SHAPE_VERTICAL_MARGIN="10 px" NUMBERED="false" FORMAT="STANDARD_FORMAT" MAX_WIDTH="10 cm" MIN_WIDTH="0 cm" BORDER_WIDTH_LIKE_EDGE="false" BORDER_WIDTH="1.9 px" BORDER_COLOR_LIKE_EDGE="true" BORDER_COLOR="#f0f0f0" BORDER_DASH_LIKE_EDGE="true" BORDER_DASH="SOLID" SHAPE_HORIZONTAL_MARGIN_QUANTITY="8 pt" SHAPE_VERTICAL_MARGIN_QUANTITY="5 pt">
<font NAME="SansSerif" SIZE="14" BOLD="false" STRIKETHROUGH="false" ITALIC="false"/>
<edge STYLE="bezier" COLOR="#93a1a1" WIDTH="3" DASH="SOLID"/>
<node TEXT="Общие положения" ID="ID_1544593487" CREATED="1685111875513" MODIFIED="1685112119238" COLOR="#ffffff" BACKGROUND_COLOR="#0066cc"/>
</node>
<node TEXT="ГОСТ 19 Единая Система программной документации" ID="ID_1512479219" CREATED="1684939613623" MODIFIED="1685112955325" ICON_SIZE="12 pt" COLOR="#ffffff" BACKGROUND_COLOR="#0066cc" STYLE="bubble" SHAPE_HORIZONTAL_MARGIN="16 px" SHAPE_VERTICAL_MARGIN="10 px" NUMBERED="false" FORMAT="STANDARD_FORMAT" MAX_WIDTH="10 cm" MIN_WIDTH="0 cm" BORDER_WIDTH_LIKE_EDGE="false" BORDER_WIDTH="1.9 px" BORDER_COLOR_LIKE_EDGE="true" BORDER_COLOR="#f0f0f0" BORDER_DASH_LIKE_EDGE="true" BORDER_DASH="SOLID" SHAPE_HORIZONTAL_MARGIN_QUANTITY="8 pt" SHAPE_VERTICAL_MARGIN_QUANTITY="5 pt" HGAP_QUANTITY="163.25 pt" VSHIFT_QUANTITY="7.5 pt">
<font NAME="SansSerif" SIZE="14" BOLD="false" STRIKETHROUGH="false" ITALIC="false"/>
<edge STYLE="bezier" COLOR="#93a1a1" WIDTH="3" DASH="SOLID"/>
<node TEXT="19.101 Виды программ и программных документов." POSITION="bottom_or_right" ID="ID_275400453" CREATED="1684939636907" MODIFIED="1685112119239" ICON_SIZE="12 pt" COLOR="#ffffff" BACKGROUND_COLOR="#0066cc" STYLE="bubble" SHAPE_HORIZONTAL_MARGIN="16 px" SHAPE_VERTICAL_MARGIN="10 px" NUMBERED="false" FORMAT="STANDARD_FORMAT" MAX_WIDTH="10 cm" MIN_WIDTH="0 cm" BORDER_WIDTH_LIKE_EDGE="false" BORDER_WIDTH="1.9 px" BORDER_COLOR_LIKE_EDGE="true" BORDER_COLOR="#f0f0f0" BORDER_DASH_LIKE_EDGE="true" BORDER_DASH="SOLID" SHAPE_HORIZONTAL_MARGIN_QUANTITY="8 pt" SHAPE_VERTICAL_MARGIN_QUANTITY="5 pt">
<font NAME="SansSerif" SIZE="12" BOLD="false" STRIKETHROUGH="false" ITALIC="false"/>
<edge STYLE="bezier" COLOR="#93a1a1" WIDTH="3" DASH="SOLID"/>
</node>
<node TEXT="19.201 Техническое задание. Требования к содержанию и оформлению" ID="ID_862045634" CREATED="1684939645058" MODIFIED="1685112119240" ICON_SIZE="12 pt" COLOR="#ffffff" BACKGROUND_COLOR="#0066cc" STYLE="bubble" SHAPE_HORIZONTAL_MARGIN="16 px" SHAPE_VERTICAL_MARGIN="10 px" NUMBERED="false" FORMAT="STANDARD_FORMAT" MAX_WIDTH="10 cm" MIN_WIDTH="0 cm" BORDER_WIDTH_LIKE_EDGE="false" BORDER_WIDTH="1.9 px" BORDER_COLOR_LIKE_EDGE="true" BORDER_COLOR="#f0f0f0" BORDER_DASH_LIKE_EDGE="true" BORDER_DASH="SOLID" SHAPE_HORIZONTAL_MARGIN_QUANTITY="8 pt" SHAPE_VERTICAL_MARGIN_QUANTITY="5 pt">
<font NAME="SansSerif" SIZE="12" BOLD="false" STRIKETHROUGH="false" ITALIC="false"/>
<edge STYLE="bezier" COLOR="#93a1a1" WIDTH="3" DASH="SOLID"/>
</node>
<node TEXT="19.402 Описание программы" ID="ID_1933607733" CREATED="1684939645058" MODIFIED="1685112119240" ICON_SIZE="12 pt" COLOR="#ffffff" BACKGROUND_COLOR="#0066cc" STYLE="bubble" SHAPE_HORIZONTAL_MARGIN="16 px" SHAPE_VERTICAL_MARGIN="10 px" NUMBERED="false" FORMAT="STANDARD_FORMAT" MAX_WIDTH="10 cm" MIN_WIDTH="0 cm" BORDER_WIDTH_LIKE_EDGE="false" BORDER_WIDTH="1.9 px" BORDER_COLOR_LIKE_EDGE="true" BORDER_COLOR="#f0f0f0" BORDER_DASH_LIKE_EDGE="true" BORDER_DASH="SOLID" SHAPE_HORIZONTAL_MARGIN_QUANTITY="8 pt" SHAPE_VERTICAL_MARGIN_QUANTITY="5 pt">
<font NAME="SansSerif" SIZE="12" BOLD="false" STRIKETHROUGH="false" ITALIC="false"/>
<edge STYLE="bezier" COLOR="#93a1a1" WIDTH="3" DASH="SOLID"/>
</node>
<node TEXT="19.404 Пояснительная записка. Требования к содержанию и оформлению" ID="ID_524103797" CREATED="1684939645058" MODIFIED="1685112119241" ICON_SIZE="12 pt" COLOR="#ffffff" BACKGROUND_COLOR="#0066cc" STYLE="bubble" SHAPE_HORIZONTAL_MARGIN="16 px" SHAPE_VERTICAL_MARGIN="10 px" NUMBERED="false" FORMAT="STANDARD_FORMAT" MAX_WIDTH="10 cm" MIN_WIDTH="0 cm" BORDER_WIDTH_LIKE_EDGE="false" BORDER_WIDTH="1.9 px" BORDER_COLOR_LIKE_EDGE="true" BORDER_COLOR="#f0f0f0" BORDER_DASH_LIKE_EDGE="true" BORDER_DASH="SOLID" SHAPE_HORIZONTAL_MARGIN_QUANTITY="8 pt" SHAPE_VERTICAL_MARGIN_QUANTITY="5 pt">
<font NAME="SansSerif" SIZE="12" BOLD="false" STRIKETHROUGH="false" ITALIC="false"/>
<edge STYLE="bezier" COLOR="#93a1a1" WIDTH="3" DASH="SOLID"/>
</node>
</node>
<node TEXT="ГОСТ Р ИСО/МЭК 15408 Информационная технология. Методы и средства обеспечения безопасности. Критерии оценки безопасности информационных технологий." ID="ID_49829127" CREATED="1684939613623" MODIFIED="1685112119241" ICON_SIZE="12 pt" COLOR="#ffffff" BACKGROUND_COLOR="#0066cc" STYLE="bubble" SHAPE_HORIZONTAL_MARGIN="16 px" SHAPE_VERTICAL_MARGIN="10 px" NUMBERED="false" FORMAT="STANDARD_FORMAT" MAX_WIDTH="10 cm" MIN_WIDTH="0 cm" BORDER_WIDTH_LIKE_EDGE="false" BORDER_WIDTH="1.9 px" BORDER_COLOR_LIKE_EDGE="true" BORDER_COLOR="#f0f0f0" BORDER_DASH_LIKE_EDGE="true" BORDER_DASH="SOLID" SHAPE_HORIZONTAL_MARGIN_QUANTITY="8 pt" SHAPE_VERTICAL_MARGIN_QUANTITY="5 pt">
<font NAME="SansSerif" SIZE="14" BOLD="false" STRIKETHROUGH="false" ITALIC="false"/>
<edge STYLE="bezier" COLOR="#93a1a1" WIDTH="3" DASH="SOLID"/>
<node TEXT="15408-1 Часть 1. Введение и общая модель" POSITION="bottom_or_right" ID="ID_20748274" CREATED="1684939636907" MODIFIED="1685112119241" ICON_SIZE="12 pt" COLOR="#ffffff" BACKGROUND_COLOR="#0066cc" STYLE="bubble" SHAPE_HORIZONTAL_MARGIN="16 px" SHAPE_VERTICAL_MARGIN="10 px" NUMBERED="false" FORMAT="STANDARD_FORMAT" MAX_WIDTH="10 cm" MIN_WIDTH="0 cm" BORDER_WIDTH_LIKE_EDGE="false" BORDER_WIDTH="1.9 px" BORDER_COLOR_LIKE_EDGE="true" BORDER_COLOR="#f0f0f0" BORDER_DASH_LIKE_EDGE="true" BORDER_DASH="SOLID" SHAPE_HORIZONTAL_MARGIN_QUANTITY="8 pt" SHAPE_VERTICAL_MARGIN_QUANTITY="5 pt">
<font NAME="SansSerif" SIZE="12" BOLD="false" STRIKETHROUGH="false" ITALIC="false"/>
<edge STYLE="bezier" COLOR="#93a1a1" WIDTH="3" DASH="SOLID"/>
</node>
<node TEXT="15408-2 Часть 2. Функциональные компоненты безопасности" ID="ID_1341092288" CREATED="1684939636907" MODIFIED="1685112119242" ICON_SIZE="12 pt" COLOR="#ffffff" BACKGROUND_COLOR="#0066cc" STYLE="bubble" SHAPE_HORIZONTAL_MARGIN="16 px" SHAPE_VERTICAL_MARGIN="10 px" NUMBERED="false" FORMAT="STANDARD_FORMAT" MAX_WIDTH="10 cm" MIN_WIDTH="0 cm" BORDER_WIDTH_LIKE_EDGE="false" BORDER_WIDTH="1.9 px" BORDER_COLOR_LIKE_EDGE="true" BORDER_COLOR="#f0f0f0" BORDER_DASH_LIKE_EDGE="true" BORDER_DASH="SOLID" SHAPE_HORIZONTAL_MARGIN_QUANTITY="8 pt" SHAPE_VERTICAL_MARGIN_QUANTITY="5 pt">
<font NAME="SansSerif" SIZE="12" BOLD="false" STRIKETHROUGH="false" ITALIC="false"/>
<edge STYLE="bezier" COLOR="#93a1a1" WIDTH="3" DASH="SOLID"/>
</node>
<node TEXT="15408-3 Часть 3. Компоненты доверия к безопасности" ID="ID_1664237261" CREATED="1684939636907" MODIFIED="1685112119231" ICON_SIZE="12 pt" COLOR="#ffffff" BACKGROUND_COLOR="#0066cc" STYLE="bubble" SHAPE_HORIZONTAL_MARGIN="16 px" SHAPE_VERTICAL_MARGIN="10 px" NUMBERED="false" FORMAT="STANDARD_FORMAT" MAX_WIDTH="10 cm" MIN_WIDTH="0 cm" BORDER_WIDTH_LIKE_EDGE="false" BORDER_WIDTH="1.9 px" BORDER_COLOR_LIKE_EDGE="true" BORDER_COLOR="#f0f0f0" BORDER_DASH_LIKE_EDGE="true" BORDER_DASH="SOLID" SHAPE_HORIZONTAL_MARGIN_QUANTITY="8 pt" SHAPE_VERTICAL_MARGIN_QUANTITY="5 pt">
<font NAME="SansSerif" SIZE="12" BOLD="false" STRIKETHROUGH="false" ITALIC="false"/>
<edge STYLE="bezier" COLOR="#93a1a1" WIDTH="3" DASH="SOLID"/>
</node>
</node>
</node>
<node TEXT="Меры по разработке безопасного программного обеспечения" POSITION="bottom_or_right" ID="ID_1136464669" CREATED="1684937241613" MODIFIED="1685112989013" ICON_SIZE="12 pt" COLOR="#ffffff" BACKGROUND_COLOR="#0033cc" STYLE="bubble" SHAPE_HORIZONTAL_MARGIN="16 px" SHAPE_VERTICAL_MARGIN="10 px" NUMBERED="false" FORMAT="STANDARD_FORMAT" TEXT_ALIGN="CENTER" MAX_WIDTH="10 cm" MIN_WIDTH="0 cm" BORDER_WIDTH_LIKE_EDGE="false" BORDER_WIDTH="1.9 px" BORDER_COLOR_LIKE_EDGE="true" BORDER_COLOR="#2c2b29" BORDER_DASH_LIKE_EDGE="true" BORDER_DASH="SOLID" HGAP_QUANTITY="59.75 pt" VSHIFT_QUANTITY="-2368.99996 pt" SHAPE_HORIZONTAL_MARGIN_QUANTITY="8 pt" SHAPE_VERTICAL_MARGIN_QUANTITY="5 pt">
<font NAME="SansSerif" SIZE="16" BOLD="false" STRIKETHROUGH="false" ITALIC="false"/>
<edge STYLE="bezier" COLOR="#93a1a1" WIDTH="3" DASH="SOLID"/>
<node TEXT="Меры по разработке безопасного программного обеспечения, реализуемые при&#xa;выполнении анализа требований к программному обеспечению" ID="ID_1809898920" CREATED="1684939514794" MODIFIED="1685112681306" ICON_SIZE="12 pt" COLOR="#ffffff" BACKGROUND_COLOR="#0066cc" STYLE="bubble" SHAPE_HORIZONTAL_MARGIN="16 px" SHAPE_VERTICAL_MARGIN="10 px" NUMBERED="false" FORMAT="STANDARD_FORMAT" MAX_WIDTH="10 cm" MIN_WIDTH="0 cm" BORDER_WIDTH_LIKE_EDGE="false" BORDER_WIDTH="1.9 px" BORDER_COLOR_LIKE_EDGE="true" BORDER_COLOR="#f0f0f0" BORDER_DASH_LIKE_EDGE="true" BORDER_DASH="SOLID" SHAPE_HORIZONTAL_MARGIN_QUANTITY="8 pt" SHAPE_VERTICAL_MARGIN_QUANTITY="5 pt">
<font NAME="SansSerif" SIZE="14" BOLD="false" STRIKETHROUGH="false" ITALIC="false"/>
<edge STYLE="bezier" COLOR="#93a1a1" WIDTH="3" DASH="SOLID"/>
<node TEXT="Меры по разработке безопасного программного обеспечения, подлежащая реализации" ID="ID_1432188015" CREATED="1684939636907" MODIFIED="1685112893464" ICON_SIZE="12 pt" COLOR="#ffffff" BACKGROUND_COLOR="#0066cc" STYLE="bubble" SHAPE_HORIZONTAL_MARGIN="16 px" SHAPE_VERTICAL_MARGIN="10 px" NUMBERED="false" FORMAT="STANDARD_FORMAT" MAX_WIDTH="10 cm" MIN_WIDTH="0 cm" BORDER_WIDTH_LIKE_EDGE="false" BORDER_WIDTH="1.9 px" BORDER_COLOR_LIKE_EDGE="true" BORDER_COLOR="#f0f0f0" BORDER_DASH_LIKE_EDGE="true" BORDER_DASH="SOLID" SHAPE_HORIZONTAL_MARGIN_QUANTITY="8 pt" SHAPE_VERTICAL_MARGIN_QUANTITY="5 pt">
<font NAME="SansSerif" SIZE="12" BOLD="false" STRIKETHROUGH="false" ITALIC="false"/>
<edge STYLE="bezier" COLOR="#93a1a1" WIDTH="3" DASH="SOLID"/>
</node>
<node TEXT="Цели и результаты реализации мер по разработке безопасного программного обеспечения" ID="ID_1688829786" CREATED="1684939636907" MODIFIED="1685113016472" ICON_SIZE="12 pt" COLOR="#ffffff" BACKGROUND_COLOR="#0066cc" STYLE="bubble" SHAPE_HORIZONTAL_MARGIN="16 px" SHAPE_VERTICAL_MARGIN="10 px" NUMBERED="false" FORMAT="STANDARD_FORMAT" MAX_WIDTH="10 cm" MIN_WIDTH="0 cm" BORDER_WIDTH_LIKE_EDGE="false" BORDER_WIDTH="1.9 px" BORDER_COLOR_LIKE_EDGE="true" BORDER_COLOR="#f0f0f0" BORDER_DASH_LIKE_EDGE="true" BORDER_DASH="SOLID" SHAPE_HORIZONTAL_MARGIN_QUANTITY="8 pt" SHAPE_VERTICAL_MARGIN_QUANTITY="5 pt">
<font NAME="SansSerif" SIZE="12" BOLD="false" STRIKETHROUGH="false" ITALIC="false"/>
<edge STYLE="bezier" COLOR="#93a1a1" WIDTH="3" DASH="SOLID"/>
</node>
<node TEXT="Требования к реализации мор по разработке безопасного программного обеспечения" ID="ID_1543855379" CREATED="1684939636907" MODIFIED="1685112705446" ICON_SIZE="12 pt" COLOR="#ffffff" BACKGROUND_COLOR="#0066cc" STYLE="bubble" SHAPE_HORIZONTAL_MARGIN="16 px" SHAPE_VERTICAL_MARGIN="10 px" NUMBERED="false" FORMAT="STANDARD_FORMAT" MAX_WIDTH="10 cm" MIN_WIDTH="0 cm" BORDER_WIDTH_LIKE_EDGE="false" BORDER_WIDTH="1.9 px" BORDER_COLOR_LIKE_EDGE="true" BORDER_COLOR="#f0f0f0" BORDER_DASH_LIKE_EDGE="true" BORDER_DASH="SOLID" SHAPE_HORIZONTAL_MARGIN_QUANTITY="8 pt" SHAPE_VERTICAL_MARGIN_QUANTITY="5 pt">
<font NAME="SansSerif" SIZE="12" BOLD="false" STRIKETHROUGH="false" ITALIC="false"/>
<edge STYLE="bezier" COLOR="#93a1a1" WIDTH="3" DASH="SOLID"/>
</node>
</node>
<node TEXT=" Меры по разработке безопасного программного обеспечения, реализуемые при&#xa;выполнении проектирования архитектуры программы" FOLDED="true" ID="ID_281240222" CREATED="1684939514794" MODIFIED="1685112715835" ICON_SIZE="12 pt" COLOR="#ffffff" BACKGROUND_COLOR="#0066cc" STYLE="bubble" SHAPE_HORIZONTAL_MARGIN="16 px" SHAPE_VERTICAL_MARGIN="10 px" NUMBERED="false" FORMAT="STANDARD_FORMAT" MAX_WIDTH="10 cm" MIN_WIDTH="0 cm" BORDER_WIDTH_LIKE_EDGE="false" BORDER_WIDTH="1.9 px" BORDER_COLOR_LIKE_EDGE="true" BORDER_COLOR="#f0f0f0" BORDER_DASH_LIKE_EDGE="true" BORDER_DASH="SOLID" SHAPE_HORIZONTAL_MARGIN_QUANTITY="8 pt" SHAPE_VERTICAL_MARGIN_QUANTITY="5 pt">
<font NAME="SansSerif" SIZE="14" BOLD="false" STRIKETHROUGH="false" ITALIC="false"/>
<edge STYLE="bezier" COLOR="#93a1a1" WIDTH="3" DASH="SOLID"/>
<node TEXT="Меры по разработке безопасного программного обеспечения, подлежащая реализации" ID="ID_1078368266" CREATED="1684939636907" MODIFIED="1685112903929" ICON_SIZE="12 pt" COLOR="#ffffff" BACKGROUND_COLOR="#0066cc" STYLE="bubble" SHAPE_HORIZONTAL_MARGIN="16 px" SHAPE_VERTICAL_MARGIN="10 px" NUMBERED="false" FORMAT="STANDARD_FORMAT" MAX_WIDTH="10 cm" MIN_WIDTH="0 cm" BORDER_WIDTH_LIKE_EDGE="false" BORDER_WIDTH="1.9 px" BORDER_COLOR_LIKE_EDGE="true" BORDER_COLOR="#f0f0f0" BORDER_DASH_LIKE_EDGE="true" BORDER_DASH="SOLID" SHAPE_HORIZONTAL_MARGIN_QUANTITY="8 pt" SHAPE_VERTICAL_MARGIN_QUANTITY="5 pt">
<font NAME="SansSerif" SIZE="12" BOLD="false" STRIKETHROUGH="false" ITALIC="false"/>
<edge STYLE="bezier" COLOR="#93a1a1" WIDTH="3" DASH="SOLID"/>
</node>
<node TEXT="Цели и результаты реализации мер по разработке безопасного программного обеспечения" ID="ID_896581086" CREATED="1684939636907" MODIFIED="1685112734585" ICON_SIZE="12 pt" COLOR="#ffffff" BACKGROUND_COLOR="#0066cc" STYLE="bubble" SHAPE_HORIZONTAL_MARGIN="16 px" SHAPE_VERTICAL_MARGIN="10 px" NUMBERED="false" FORMAT="STANDARD_FORMAT" MAX_WIDTH="10 cm" MIN_WIDTH="0 cm" BORDER_WIDTH_LIKE_EDGE="false" BORDER_WIDTH="1.9 px" BORDER_COLOR_LIKE_EDGE="true" BORDER_COLOR="#f0f0f0" BORDER_DASH_LIKE_EDGE="true" BORDER_DASH="SOLID" SHAPE_HORIZONTAL_MARGIN_QUANTITY="8 pt" SHAPE_VERTICAL_MARGIN_QUANTITY="5 pt">
<font NAME="SansSerif" SIZE="12" BOLD="false" STRIKETHROUGH="false" ITALIC="false"/>
<edge STYLE="bezier" COLOR="#93a1a1" WIDTH="3" DASH="SOLID"/>
</node>
<node TEXT="Требования к реализации мер по разработке безопасного программного обеспечения" ID="ID_983459027" CREATED="1684939636907" MODIFIED="1685112737696" ICON_SIZE="12 pt" COLOR="#ffffff" BACKGROUND_COLOR="#0066cc" STYLE="bubble" SHAPE_HORIZONTAL_MARGIN="16 px" SHAPE_VERTICAL_MARGIN="10 px" NUMBERED="false" FORMAT="STANDARD_FORMAT" MAX_WIDTH="10 cm" MIN_WIDTH="0 cm" BORDER_WIDTH_LIKE_EDGE="false" BORDER_WIDTH="1.9 px" BORDER_COLOR_LIKE_EDGE="true" BORDER_COLOR="#f0f0f0" BORDER_DASH_LIKE_EDGE="true" BORDER_DASH="SOLID" SHAPE_HORIZONTAL_MARGIN_QUANTITY="8 pt" SHAPE_VERTICAL_MARGIN_QUANTITY="5 pt">
<font NAME="SansSerif" SIZE="12" BOLD="false" STRIKETHROUGH="false" ITALIC="false"/>
<edge STYLE="bezier" COLOR="#93a1a1" WIDTH="3" DASH="SOLID"/>
</node>
</node>
<node TEXT="Меры по разработке безопасного программного обеспечения, реализуемые при&#xa;выполнении конструирования и комплексирования программного обеспечения" FOLDED="true" ID="ID_564288615" CREATED="1684939514794" MODIFIED="1685112780888" ICON_SIZE="12 pt" COLOR="#ffffff" BACKGROUND_COLOR="#0066cc" STYLE="bubble" SHAPE_HORIZONTAL_MARGIN="16 px" SHAPE_VERTICAL_MARGIN="10 px" NUMBERED="false" FORMAT="STANDARD_FORMAT" MAX_WIDTH="10 cm" MIN_WIDTH="0 cm" BORDER_WIDTH_LIKE_EDGE="false" BORDER_WIDTH="1.9 px" BORDER_COLOR_LIKE_EDGE="true" BORDER_COLOR="#f0f0f0" BORDER_DASH_LIKE_EDGE="true" BORDER_DASH="SOLID" SHAPE_HORIZONTAL_MARGIN_QUANTITY="8 pt" SHAPE_VERTICAL_MARGIN_QUANTITY="5 pt">
<font NAME="SansSerif" SIZE="14" BOLD="false" STRIKETHROUGH="false" ITALIC="false"/>
<edge STYLE="bezier" COLOR="#93a1a1" WIDTH="3" DASH="SOLID"/>
<node TEXT="Меры по разработке безопасного программного обеспечения, подлежащая реализации" ID="ID_715821754" CREATED="1684939636907" MODIFIED="1685112905658" ICON_SIZE="12 pt" COLOR="#ffffff" BACKGROUND_COLOR="#0066cc" STYLE="bubble" SHAPE_HORIZONTAL_MARGIN="16 px" SHAPE_VERTICAL_MARGIN="10 px" NUMBERED="false" FORMAT="STANDARD_FORMAT" MAX_WIDTH="10 cm" MIN_WIDTH="0 cm" BORDER_WIDTH_LIKE_EDGE="false" BORDER_WIDTH="1.9 px" BORDER_COLOR_LIKE_EDGE="true" BORDER_COLOR="#f0f0f0" BORDER_DASH_LIKE_EDGE="true" BORDER_DASH="SOLID" SHAPE_HORIZONTAL_MARGIN_QUANTITY="8 pt" SHAPE_VERTICAL_MARGIN_QUANTITY="5 pt">
<font NAME="SansSerif" SIZE="12" BOLD="false" STRIKETHROUGH="false" ITALIC="false"/>
<edge STYLE="bezier" COLOR="#93a1a1" WIDTH="3" DASH="SOLID"/>
</node>
<node TEXT="Цели и результаты реализации мер по разработке безопасного программного обеспечения" ID="ID_1477354566" CREATED="1684939636907" MODIFIED="1685112734585" ICON_SIZE="12 pt" COLOR="#ffffff" BACKGROUND_COLOR="#0066cc" STYLE="bubble" SHAPE_HORIZONTAL_MARGIN="16 px" SHAPE_VERTICAL_MARGIN="10 px" NUMBERED="false" FORMAT="STANDARD_FORMAT" MAX_WIDTH="10 cm" MIN_WIDTH="0 cm" BORDER_WIDTH_LIKE_EDGE="false" BORDER_WIDTH="1.9 px" BORDER_COLOR_LIKE_EDGE="true" BORDER_COLOR="#f0f0f0" BORDER_DASH_LIKE_EDGE="true" BORDER_DASH="SOLID" SHAPE_HORIZONTAL_MARGIN_QUANTITY="8 pt" SHAPE_VERTICAL_MARGIN_QUANTITY="5 pt">
<font NAME="SansSerif" SIZE="12" BOLD="false" STRIKETHROUGH="false" ITALIC="false"/>
<edge STYLE="bezier" COLOR="#93a1a1" WIDTH="3" DASH="SOLID"/>
</node>
<node TEXT="Требования к реализации мер по разработке безопасного программного обеспечения" ID="ID_314404902" CREATED="1684939636907" MODIFIED="1685112737696" ICON_SIZE="12 pt" COLOR="#ffffff" BACKGROUND_COLOR="#0066cc" STYLE="bubble" SHAPE_HORIZONTAL_MARGIN="16 px" SHAPE_VERTICAL_MARGIN="10 px" NUMBERED="false" FORMAT="STANDARD_FORMAT" MAX_WIDTH="10 cm" MIN_WIDTH="0 cm" BORDER_WIDTH_LIKE_EDGE="false" BORDER_WIDTH="1.9 px" BORDER_COLOR_LIKE_EDGE="true" BORDER_COLOR="#f0f0f0" BORDER_DASH_LIKE_EDGE="true" BORDER_DASH="SOLID" SHAPE_HORIZONTAL_MARGIN_QUANTITY="8 pt" SHAPE_VERTICAL_MARGIN_QUANTITY="5 pt">
<font NAME="SansSerif" SIZE="12" BOLD="false" STRIKETHROUGH="false" ITALIC="false"/>
<edge STYLE="bezier" COLOR="#93a1a1" WIDTH="3" DASH="SOLID"/>
</node>
</node>
<node TEXT="Меры по разработке безопасного программного обеспечения, реализуемые при&#xa;выполнении квалификационного тестирования программного обеспечения" FOLDED="true" ID="ID_1263258812" CREATED="1684939514794" MODIFIED="1685112801763" ICON_SIZE="12 pt" COLOR="#ffffff" BACKGROUND_COLOR="#0066cc" STYLE="bubble" SHAPE_HORIZONTAL_MARGIN="16 px" SHAPE_VERTICAL_MARGIN="10 px" NUMBERED="false" FORMAT="STANDARD_FORMAT" MAX_WIDTH="10 cm" MIN_WIDTH="0 cm" BORDER_WIDTH_LIKE_EDGE="false" BORDER_WIDTH="1.9 px" BORDER_COLOR_LIKE_EDGE="true" BORDER_COLOR="#f0f0f0" BORDER_DASH_LIKE_EDGE="true" BORDER_DASH="SOLID" SHAPE_HORIZONTAL_MARGIN_QUANTITY="8 pt" SHAPE_VERTICAL_MARGIN_QUANTITY="5 pt">
<font NAME="SansSerif" SIZE="14" BOLD="false" STRIKETHROUGH="false" ITALIC="false"/>
<edge STYLE="bezier" COLOR="#93a1a1" WIDTH="3" DASH="SOLID"/>
<node TEXT="Меры по разработке безопасного программного обеспечения, подлежащая реализации" ID="ID_1544223314" CREATED="1684939636907" MODIFIED="1685112910289" ICON_SIZE="12 pt" COLOR="#ffffff" BACKGROUND_COLOR="#0066cc" STYLE="bubble" SHAPE_HORIZONTAL_MARGIN="16 px" SHAPE_VERTICAL_MARGIN="10 px" NUMBERED="false" FORMAT="STANDARD_FORMAT" MAX_WIDTH="10 cm" MIN_WIDTH="0 cm" BORDER_WIDTH_LIKE_EDGE="false" BORDER_WIDTH="1.9 px" BORDER_COLOR_LIKE_EDGE="true" BORDER_COLOR="#f0f0f0" BORDER_DASH_LIKE_EDGE="true" BORDER_DASH="SOLID" SHAPE_HORIZONTAL_MARGIN_QUANTITY="8 pt" SHAPE_VERTICAL_MARGIN_QUANTITY="5 pt">
<font NAME="SansSerif" SIZE="12" BOLD="false" STRIKETHROUGH="false" ITALIC="false"/>
<edge STYLE="bezier" COLOR="#93a1a1" WIDTH="3" DASH="SOLID"/>
</node>
<node TEXT="Цели и результаты реализации мер по разработке безопасного программного обеспечения" ID="ID_1893207224" CREATED="1684939636907" MODIFIED="1685112734585" ICON_SIZE="12 pt" COLOR="#ffffff" BACKGROUND_COLOR="#0066cc" STYLE="bubble" SHAPE_HORIZONTAL_MARGIN="16 px" SHAPE_VERTICAL_MARGIN="10 px" NUMBERED="false" FORMAT="STANDARD_FORMAT" MAX_WIDTH="10 cm" MIN_WIDTH="0 cm" BORDER_WIDTH_LIKE_EDGE="false" BORDER_WIDTH="1.9 px" BORDER_COLOR_LIKE_EDGE="true" BORDER_COLOR="#f0f0f0" BORDER_DASH_LIKE_EDGE="true" BORDER_DASH="SOLID" SHAPE_HORIZONTAL_MARGIN_QUANTITY="8 pt" SHAPE_VERTICAL_MARGIN_QUANTITY="5 pt">
<font NAME="SansSerif" SIZE="12" BOLD="false" STRIKETHROUGH="false" ITALIC="false"/>
<edge STYLE="bezier" COLOR="#93a1a1" WIDTH="3" DASH="SOLID"/>
</node>
<node TEXT="Требования к реализации мер по разработке безопасного программного обеспечения" ID="ID_492564411" CREATED="1684939636907" MODIFIED="1685112737696" ICON_SIZE="12 pt" COLOR="#ffffff" BACKGROUND_COLOR="#0066cc" STYLE="bubble" SHAPE_HORIZONTAL_MARGIN="16 px" SHAPE_VERTICAL_MARGIN="10 px" NUMBERED="false" FORMAT="STANDARD_FORMAT" MAX_WIDTH="10 cm" MIN_WIDTH="0 cm" BORDER_WIDTH_LIKE_EDGE="false" BORDER_WIDTH="1.9 px" BORDER_COLOR_LIKE_EDGE="true" BORDER_COLOR="#f0f0f0" BORDER_DASH_LIKE_EDGE="true" BORDER_DASH="SOLID" SHAPE_HORIZONTAL_MARGIN_QUANTITY="8 pt" SHAPE_VERTICAL_MARGIN_QUANTITY="5 pt">
<font NAME="SansSerif" SIZE="12" BOLD="false" STRIKETHROUGH="false" ITALIC="false"/>
<edge STYLE="bezier" COLOR="#93a1a1" WIDTH="3" DASH="SOLID"/>
</node>
</node>
<node TEXT="Меры по разработке безопасного программного обеспечения, реализуемые при&#xa;выполнении инсталляции программы и поддержки приемки программного обеспечения" FOLDED="true" ID="ID_1434838936" CREATED="1684939514794" MODIFIED="1685113028954" ICON_SIZE="12 pt" COLOR="#ffffff" BACKGROUND_COLOR="#0066cc" STYLE="bubble" SHAPE_HORIZONTAL_MARGIN="16 px" SHAPE_VERTICAL_MARGIN="10 px" NUMBERED="false" FORMAT="STANDARD_FORMAT" MAX_WIDTH="10 cm" MIN_WIDTH="0 cm" BORDER_WIDTH_LIKE_EDGE="false" BORDER_WIDTH="1.9 px" BORDER_COLOR_LIKE_EDGE="true" BORDER_COLOR="#f0f0f0" BORDER_DASH_LIKE_EDGE="true" BORDER_DASH="SOLID" SHAPE_HORIZONTAL_MARGIN_QUANTITY="8 pt" SHAPE_VERTICAL_MARGIN_QUANTITY="5 pt">
<font NAME="SansSerif" SIZE="14" BOLD="false" STRIKETHROUGH="false" ITALIC="false"/>
<edge STYLE="bezier" COLOR="#93a1a1" WIDTH="3" DASH="SOLID"/>
<node TEXT="Меры по разработке безопасного программного обеспечения, подлежащая реализации" ID="ID_239354950" CREATED="1684939636907" MODIFIED="1685112911081" ICON_SIZE="12 pt" COLOR="#ffffff" BACKGROUND_COLOR="#0066cc" STYLE="bubble" SHAPE_HORIZONTAL_MARGIN="16 px" SHAPE_VERTICAL_MARGIN="10 px" NUMBERED="false" FORMAT="STANDARD_FORMAT" MAX_WIDTH="10 cm" MIN_WIDTH="0 cm" BORDER_WIDTH_LIKE_EDGE="false" BORDER_WIDTH="1.9 px" BORDER_COLOR_LIKE_EDGE="true" BORDER_COLOR="#f0f0f0" BORDER_DASH_LIKE_EDGE="true" BORDER_DASH="SOLID" SHAPE_HORIZONTAL_MARGIN_QUANTITY="8 pt" SHAPE_VERTICAL_MARGIN_QUANTITY="5 pt">
<font NAME="SansSerif" SIZE="12" BOLD="false" STRIKETHROUGH="false" ITALIC="false"/>
<edge STYLE="bezier" COLOR="#93a1a1" WIDTH="3" DASH="SOLID"/>
</node>
<node TEXT="Цели и результаты реализации мер по разработке безопасного программного обеспечения" ID="ID_1393029973" CREATED="1684939636907" MODIFIED="1685113028952" ICON_SIZE="12 pt" COLOR="#ffffff" BACKGROUND_COLOR="#0066cc" STYLE="bubble" SHAPE_HORIZONTAL_MARGIN="16 px" SHAPE_VERTICAL_MARGIN="10 px" NUMBERED="false" FORMAT="STANDARD_FORMAT" MAX_WIDTH="10 cm" MIN_WIDTH="0 cm" BORDER_WIDTH_LIKE_EDGE="false" BORDER_WIDTH="1.9 px" BORDER_COLOR_LIKE_EDGE="true" BORDER_COLOR="#f0f0f0" BORDER_DASH_LIKE_EDGE="true" BORDER_DASH="SOLID" SHAPE_HORIZONTAL_MARGIN_QUANTITY="8 pt" SHAPE_VERTICAL_MARGIN_QUANTITY="5 pt">
<font NAME="SansSerif" SIZE="12" BOLD="false" STRIKETHROUGH="false" ITALIC="false"/>
<edge STYLE="bezier" COLOR="#93a1a1" WIDTH="3" DASH="SOLID"/>
</node>
<node TEXT="Требования к реализации мер по разработке безопасного программного обеспечения" ID="ID_1888569196" CREATED="1684939636907" MODIFIED="1685112737696" ICON_SIZE="12 pt" COLOR="#ffffff" BACKGROUND_COLOR="#0066cc" STYLE="bubble" SHAPE_HORIZONTAL_MARGIN="16 px" SHAPE_VERTICAL_MARGIN="10 px" NUMBERED="false" FORMAT="STANDARD_FORMAT" MAX_WIDTH="10 cm" MIN_WIDTH="0 cm" BORDER_WIDTH_LIKE_EDGE="false" BORDER_WIDTH="1.9 px" BORDER_COLOR_LIKE_EDGE="true" BORDER_COLOR="#f0f0f0" BORDER_DASH_LIKE_EDGE="true" BORDER_DASH="SOLID" SHAPE_HORIZONTAL_MARGIN_QUANTITY="8 pt" SHAPE_VERTICAL_MARGIN_QUANTITY="5 pt">
<font NAME="SansSerif" SIZE="12" BOLD="false" STRIKETHROUGH="false" ITALIC="false"/>
<edge STYLE="bezier" COLOR="#93a1a1" WIDTH="3" DASH="SOLID"/>
</node>
</node>
<node TEXT="Меры по разработке безопасного программного обеспечения, реализуемые при&#xa;решении проблем в программном обеспечении в процессе эксплуатации" FOLDED="true" ID="ID_844413182" CREATED="1684939514794" MODIFIED="1685113031823" ICON_SIZE="12 pt" COLOR="#ffffff" BACKGROUND_COLOR="#0066cc" STYLE="bubble" SHAPE_HORIZONTAL_MARGIN="16 px" SHAPE_VERTICAL_MARGIN="10 px" NUMBERED="false" FORMAT="STANDARD_FORMAT" MAX_WIDTH="10 cm" MIN_WIDTH="0 cm" BORDER_WIDTH_LIKE_EDGE="false" BORDER_WIDTH="1.9 px" BORDER_COLOR_LIKE_EDGE="true" BORDER_COLOR="#f0f0f0" BORDER_DASH_LIKE_EDGE="true" BORDER_DASH="SOLID" SHAPE_HORIZONTAL_MARGIN_QUANTITY="8 pt" SHAPE_VERTICAL_MARGIN_QUANTITY="5 pt">
<font NAME="SansSerif" SIZE="14" BOLD="false" STRIKETHROUGH="false" ITALIC="false"/>
<edge STYLE="bezier" COLOR="#93a1a1" WIDTH="3" DASH="SOLID"/>
<node TEXT="Меры по разработке безопасного программного обеспечения, подлежащая реализации" ID="ID_1235347384" CREATED="1684939636907" MODIFIED="1685112911835" ICON_SIZE="12 pt" COLOR="#ffffff" BACKGROUND_COLOR="#0066cc" STYLE="bubble" SHAPE_HORIZONTAL_MARGIN="16 px" SHAPE_VERTICAL_MARGIN="10 px" NUMBERED="false" FORMAT="STANDARD_FORMAT" MAX_WIDTH="10 cm" MIN_WIDTH="0 cm" BORDER_WIDTH_LIKE_EDGE="false" BORDER_WIDTH="1.9 px" BORDER_COLOR_LIKE_EDGE="true" BORDER_COLOR="#f0f0f0" BORDER_DASH_LIKE_EDGE="true" BORDER_DASH="SOLID" SHAPE_HORIZONTAL_MARGIN_QUANTITY="8 pt" SHAPE_VERTICAL_MARGIN_QUANTITY="5 pt">
<font NAME="SansSerif" SIZE="12" BOLD="false" STRIKETHROUGH="false" ITALIC="false"/>
<edge STYLE="bezier" COLOR="#93a1a1" WIDTH="3" DASH="SOLID"/>
</node>
<node TEXT="Цели и результаты реализации мер по разработке безопасного программного обеспечения" ID="ID_1569849640" CREATED="1684939636907" MODIFIED="1685113031822" ICON_SIZE="12 pt" COLOR="#ffffff" BACKGROUND_COLOR="#0066cc" STYLE="bubble" SHAPE_HORIZONTAL_MARGIN="16 px" SHAPE_VERTICAL_MARGIN="10 px" NUMBERED="false" FORMAT="STANDARD_FORMAT" MAX_WIDTH="10 cm" MIN_WIDTH="0 cm" BORDER_WIDTH_LIKE_EDGE="false" BORDER_WIDTH="1.9 px" BORDER_COLOR_LIKE_EDGE="true" BORDER_COLOR="#f0f0f0" BORDER_DASH_LIKE_EDGE="true" BORDER_DASH="SOLID" SHAPE_HORIZONTAL_MARGIN_QUANTITY="8 pt" SHAPE_VERTICAL_MARGIN_QUANTITY="5 pt">
<font NAME="SansSerif" SIZE="12" BOLD="false" STRIKETHROUGH="false" ITALIC="false"/>
<edge STYLE="bezier" COLOR="#93a1a1" WIDTH="3" DASH="SOLID"/>
</node>
<node TEXT="Требования к реализации мер по разработке безопасного программного обеспечения" ID="ID_175264283" CREATED="1684939636907" MODIFIED="1685112737696" ICON_SIZE="12 pt" COLOR="#ffffff" BACKGROUND_COLOR="#0066cc" STYLE="bubble" SHAPE_HORIZONTAL_MARGIN="16 px" SHAPE_VERTICAL_MARGIN="10 px" NUMBERED="false" FORMAT="STANDARD_FORMAT" MAX_WIDTH="10 cm" MIN_WIDTH="0 cm" BORDER_WIDTH_LIKE_EDGE="false" BORDER_WIDTH="1.9 px" BORDER_COLOR_LIKE_EDGE="true" BORDER_COLOR="#f0f0f0" BORDER_DASH_LIKE_EDGE="true" BORDER_DASH="SOLID" SHAPE_HORIZONTAL_MARGIN_QUANTITY="8 pt" SHAPE_VERTICAL_MARGIN_QUANTITY="5 pt">
<font NAME="SansSerif" SIZE="12" BOLD="false" STRIKETHROUGH="false" ITALIC="false"/>
<edge STYLE="bezier" COLOR="#93a1a1" WIDTH="3" DASH="SOLID"/>
</node>
</node>
<node TEXT="Меры по разработке безопасного программного обеспечения, реализуемые в процессе&#xa;менеджмента документацией и конфигурацией программы" FOLDED="true" ID="ID_1008296130" CREATED="1684939514794" MODIFIED="1685113068283" ICON_SIZE="12 pt" COLOR="#ffffff" BACKGROUND_COLOR="#0066cc" STYLE="bubble" SHAPE_HORIZONTAL_MARGIN="16 px" SHAPE_VERTICAL_MARGIN="10 px" NUMBERED="false" FORMAT="STANDARD_FORMAT" MAX_WIDTH="10 cm" MIN_WIDTH="0 cm" BORDER_WIDTH_LIKE_EDGE="false" BORDER_WIDTH="1.9 px" BORDER_COLOR_LIKE_EDGE="true" BORDER_COLOR="#f0f0f0" BORDER_DASH_LIKE_EDGE="true" BORDER_DASH="SOLID" SHAPE_HORIZONTAL_MARGIN_QUANTITY="8 pt" SHAPE_VERTICAL_MARGIN_QUANTITY="5 pt">
<font NAME="SansSerif" SIZE="14" BOLD="false" STRIKETHROUGH="false" ITALIC="false"/>
<edge STYLE="bezier" COLOR="#93a1a1" WIDTH="3" DASH="SOLID"/>
<node TEXT="Меры по разработке безопасного программного обеспечения, подлежащая реализации" ID="ID_263074287" CREATED="1684939636907" MODIFIED="1685112911835" ICON_SIZE="12 pt" COLOR="#ffffff" BACKGROUND_COLOR="#0066cc" STYLE="bubble" SHAPE_HORIZONTAL_MARGIN="16 px" SHAPE_VERTICAL_MARGIN="10 px" NUMBERED="false" FORMAT="STANDARD_FORMAT" MAX_WIDTH="10 cm" MIN_WIDTH="0 cm" BORDER_WIDTH_LIKE_EDGE="false" BORDER_WIDTH="1.9 px" BORDER_COLOR_LIKE_EDGE="true" BORDER_COLOR="#f0f0f0" BORDER_DASH_LIKE_EDGE="true" BORDER_DASH="SOLID" SHAPE_HORIZONTAL_MARGIN_QUANTITY="8 pt" SHAPE_VERTICAL_MARGIN_QUANTITY="5 pt">
<font NAME="SansSerif" SIZE="12" BOLD="false" STRIKETHROUGH="false" ITALIC="false"/>
<edge STYLE="bezier" COLOR="#93a1a1" WIDTH="3" DASH="SOLID"/>
</node>
<node TEXT="Цели и результаты реализации мер по разработке безопасного программного обеспечения" ID="ID_283638480" CREATED="1684939636907" MODIFIED="1685113068282" ICON_SIZE="12 pt" COLOR="#ffffff" BACKGROUND_COLOR="#0066cc" STYLE="bubble" SHAPE_HORIZONTAL_MARGIN="16 px" SHAPE_VERTICAL_MARGIN="10 px" NUMBERED="false" FORMAT="STANDARD_FORMAT" MAX_WIDTH="10 cm" MIN_WIDTH="0 cm" BORDER_WIDTH_LIKE_EDGE="false" BORDER_WIDTH="1.9 px" BORDER_COLOR_LIKE_EDGE="true" BORDER_COLOR="#f0f0f0" BORDER_DASH_LIKE_EDGE="true" BORDER_DASH="SOLID" SHAPE_HORIZONTAL_MARGIN_QUANTITY="8 pt" SHAPE_VERTICAL_MARGIN_QUANTITY="5 pt">
<font NAME="SansSerif" SIZE="12" BOLD="false" STRIKETHROUGH="false" ITALIC="false"/>
<edge STYLE="bezier" COLOR="#93a1a1" WIDTH="3" DASH="SOLID"/>
</node>
<node TEXT="Требования к реализации мер по разработке безопасного программного обеспечения" ID="ID_1672767083" CREATED="1684939636907" MODIFIED="1685112737696" ICON_SIZE="12 pt" COLOR="#ffffff" BACKGROUND_COLOR="#0066cc" STYLE="bubble" SHAPE_HORIZONTAL_MARGIN="16 px" SHAPE_VERTICAL_MARGIN="10 px" NUMBERED="false" FORMAT="STANDARD_FORMAT" MAX_WIDTH="10 cm" MIN_WIDTH="0 cm" BORDER_WIDTH_LIKE_EDGE="false" BORDER_WIDTH="1.9 px" BORDER_COLOR_LIKE_EDGE="true" BORDER_COLOR="#f0f0f0" BORDER_DASH_LIKE_EDGE="true" BORDER_DASH="SOLID" SHAPE_HORIZONTAL_MARGIN_QUANTITY="8 pt" SHAPE_VERTICAL_MARGIN_QUANTITY="5 pt">
<font NAME="SansSerif" SIZE="12" BOLD="false" STRIKETHROUGH="false" ITALIC="false"/>
<edge STYLE="bezier" COLOR="#93a1a1" WIDTH="3" DASH="SOLID"/>
</node>
</node>
<node TEXT="Меры по разработке безопасного программного обеспечения, реализуемые в процессе&#xa;менеджмента инфраструктурой среды разработки программного обеспечения" FOLDED="true" ID="ID_24298328" CREATED="1684939514794" MODIFIED="1685113082674" ICON_SIZE="12 pt" COLOR="#ffffff" BACKGROUND_COLOR="#0066cc" STYLE="bubble" SHAPE_HORIZONTAL_MARGIN="16 px" SHAPE_VERTICAL_MARGIN="10 px" NUMBERED="false" FORMAT="STANDARD_FORMAT" MAX_WIDTH="10 cm" MIN_WIDTH="0 cm" BORDER_WIDTH_LIKE_EDGE="false" BORDER_WIDTH="1.9 px" BORDER_COLOR_LIKE_EDGE="true" BORDER_COLOR="#f0f0f0" BORDER_DASH_LIKE_EDGE="true" BORDER_DASH="SOLID" SHAPE_HORIZONTAL_MARGIN_QUANTITY="8 pt" SHAPE_VERTICAL_MARGIN_QUANTITY="5 pt">
<font NAME="SansSerif" SIZE="14" BOLD="false" STRIKETHROUGH="false" ITALIC="false"/>
<edge STYLE="bezier" COLOR="#93a1a1" WIDTH="3" DASH="SOLID"/>
<node TEXT="Меры по разработке безопасного программного обеспечения, подлежащая реализации" ID="ID_103540301" CREATED="1684939636907" MODIFIED="1685112911835" ICON_SIZE="12 pt" COLOR="#ffffff" BACKGROUND_COLOR="#0066cc" STYLE="bubble" SHAPE_HORIZONTAL_MARGIN="16 px" SHAPE_VERTICAL_MARGIN="10 px" NUMBERED="false" FORMAT="STANDARD_FORMAT" MAX_WIDTH="10 cm" MIN_WIDTH="0 cm" BORDER_WIDTH_LIKE_EDGE="false" BORDER_WIDTH="1.9 px" BORDER_COLOR_LIKE_EDGE="true" BORDER_COLOR="#f0f0f0" BORDER_DASH_LIKE_EDGE="true" BORDER_DASH="SOLID" SHAPE_HORIZONTAL_MARGIN_QUANTITY="8 pt" SHAPE_VERTICAL_MARGIN_QUANTITY="5 pt">
<font NAME="SansSerif" SIZE="12" BOLD="false" STRIKETHROUGH="false" ITALIC="false"/>
<edge STYLE="bezier" COLOR="#93a1a1" WIDTH="3" DASH="SOLID"/>
</node>
<node TEXT="Цели и результаты реализации мер по разработке безопасного программного обеспечения" ID="ID_880715052" CREATED="1684939636907" MODIFIED="1685113031822" ICON_SIZE="12 pt" COLOR="#ffffff" BACKGROUND_COLOR="#0066cc" STYLE="bubble" SHAPE_HORIZONTAL_MARGIN="16 px" SHAPE_VERTICAL_MARGIN="10 px" NUMBERED="false" FORMAT="STANDARD_FORMAT" MAX_WIDTH="10 cm" MIN_WIDTH="0 cm" BORDER_WIDTH_LIKE_EDGE="false" BORDER_WIDTH="1.9 px" BORDER_COLOR_LIKE_EDGE="true" BORDER_COLOR="#f0f0f0" BORDER_DASH_LIKE_EDGE="true" BORDER_DASH="SOLID" SHAPE_HORIZONTAL_MARGIN_QUANTITY="8 pt" SHAPE_VERTICAL_MARGIN_QUANTITY="5 pt">
<font NAME="SansSerif" SIZE="12" BOLD="false" STRIKETHROUGH="false" ITALIC="false"/>
<edge STYLE="bezier" COLOR="#93a1a1" WIDTH="3" DASH="SOLID"/>
</node>
<node TEXT="Требования к реализации мер по разработке безопасного программного обеспечения" ID="ID_1612017434" CREATED="1684939636907" MODIFIED="1685112737696" ICON_SIZE="12 pt" COLOR="#ffffff" BACKGROUND_COLOR="#0066cc" STYLE="bubble" SHAPE_HORIZONTAL_MARGIN="16 px" SHAPE_VERTICAL_MARGIN="10 px" NUMBERED="false" FORMAT="STANDARD_FORMAT" MAX_WIDTH="10 cm" MIN_WIDTH="0 cm" BORDER_WIDTH_LIKE_EDGE="false" BORDER_WIDTH="1.9 px" BORDER_COLOR_LIKE_EDGE="true" BORDER_COLOR="#f0f0f0" BORDER_DASH_LIKE_EDGE="true" BORDER_DASH="SOLID" SHAPE_HORIZONTAL_MARGIN_QUANTITY="8 pt" SHAPE_VERTICAL_MARGIN_QUANTITY="5 pt">
<font NAME="SansSerif" SIZE="12" BOLD="false" STRIKETHROUGH="false" ITALIC="false"/>
<edge STYLE="bezier" COLOR="#93a1a1" WIDTH="3" DASH="SOLID"/>
</node>
</node>
<node TEXT="Меры по разработке безопасного программного обеспечения, реализуемые в процессе&#xa;менеджмента людскими ресурсами" FOLDED="true" ID="ID_241841550" CREATED="1684939514794" MODIFIED="1685113133143" ICON_SIZE="12 pt" COLOR="#ffffff" BACKGROUND_COLOR="#0066cc" STYLE="bubble" SHAPE_HORIZONTAL_MARGIN="16 px" SHAPE_VERTICAL_MARGIN="10 px" NUMBERED="false" FORMAT="STANDARD_FORMAT" MAX_WIDTH="10 cm" MIN_WIDTH="0 cm" BORDER_WIDTH_LIKE_EDGE="false" BORDER_WIDTH="1.9 px" BORDER_COLOR_LIKE_EDGE="true" BORDER_COLOR="#f0f0f0" BORDER_DASH_LIKE_EDGE="true" BORDER_DASH="SOLID" SHAPE_HORIZONTAL_MARGIN_QUANTITY="8 pt" SHAPE_VERTICAL_MARGIN_QUANTITY="5 pt">
<font NAME="SansSerif" SIZE="14" BOLD="false" STRIKETHROUGH="false" ITALIC="false"/>
<edge STYLE="bezier" COLOR="#93a1a1" WIDTH="3" DASH="SOLID"/>
<node TEXT="Меры по разработке безопасного программного обеспечения, подлежащая реализации" ID="ID_1823361800" CREATED="1684939636907" MODIFIED="1685112911835" ICON_SIZE="12 pt" COLOR="#ffffff" BACKGROUND_COLOR="#0066cc" STYLE="bubble" SHAPE_HORIZONTAL_MARGIN="16 px" SHAPE_VERTICAL_MARGIN="10 px" NUMBERED="false" FORMAT="STANDARD_FORMAT" MAX_WIDTH="10 cm" MIN_WIDTH="0 cm" BORDER_WIDTH_LIKE_EDGE="false" BORDER_WIDTH="1.9 px" BORDER_COLOR_LIKE_EDGE="true" BORDER_COLOR="#f0f0f0" BORDER_DASH_LIKE_EDGE="true" BORDER_DASH="SOLID" SHAPE_HORIZONTAL_MARGIN_QUANTITY="8 pt" SHAPE_VERTICAL_MARGIN_QUANTITY="5 pt">
<font NAME="SansSerif" SIZE="12" BOLD="false" STRIKETHROUGH="false" ITALIC="false"/>
<edge STYLE="bezier" COLOR="#93a1a1" WIDTH="3" DASH="SOLID"/>
</node>
<node TEXT="Цели и результаты реализации мер по разработке безопасного программного обеспечения" ID="ID_1916477820" CREATED="1684939636907" MODIFIED="1685113133142" ICON_SIZE="12 pt" COLOR="#ffffff" BACKGROUND_COLOR="#0066cc" STYLE="bubble" SHAPE_HORIZONTAL_MARGIN="16 px" SHAPE_VERTICAL_MARGIN="10 px" NUMBERED="false" FORMAT="STANDARD_FORMAT" MAX_WIDTH="10 cm" MIN_WIDTH="0 cm" BORDER_WIDTH_LIKE_EDGE="false" BORDER_WIDTH="1.9 px" BORDER_COLOR_LIKE_EDGE="true" BORDER_COLOR="#f0f0f0" BORDER_DASH_LIKE_EDGE="true" BORDER_DASH="SOLID" SHAPE_HORIZONTAL_MARGIN_QUANTITY="8 pt" SHAPE_VERTICAL_MARGIN_QUANTITY="5 pt">
<font NAME="SansSerif" SIZE="12" BOLD="false" STRIKETHROUGH="false" ITALIC="false"/>
<edge STYLE="bezier" COLOR="#93a1a1" WIDTH="3" DASH="SOLID"/>
</node>
<node TEXT="Требования к реализации мер по разработке безопасного программного обеспечения" ID="ID_1751658917" CREATED="1684939636907" MODIFIED="1685112737696" ICON_SIZE="12 pt" COLOR="#ffffff" BACKGROUND_COLOR="#0066cc" STYLE="bubble" SHAPE_HORIZONTAL_MARGIN="16 px" SHAPE_VERTICAL_MARGIN="10 px" NUMBERED="false" FORMAT="STANDARD_FORMAT" MAX_WIDTH="10 cm" MIN_WIDTH="0 cm" BORDER_WIDTH_LIKE_EDGE="false" BORDER_WIDTH="1.9 px" BORDER_COLOR_LIKE_EDGE="true" BORDER_COLOR="#f0f0f0" BORDER_DASH_LIKE_EDGE="true" BORDER_DASH="SOLID" SHAPE_HORIZONTAL_MARGIN_QUANTITY="8 pt" SHAPE_VERTICAL_MARGIN_QUANTITY="5 pt">
<font NAME="SansSerif" SIZE="12" BOLD="false" STRIKETHROUGH="false" ITALIC="false"/>
<edge STYLE="bezier" COLOR="#93a1a1" WIDTH="3" DASH="SOLID"/>
</node>
</node>
</node>
<node TEXT="Термины и определения" POSITION="top_or_left" ID="ID_1227674445" CREATED="1684937230752" MODIFIED="1685112935912" ICON_SIZE="12 pt" COLOR="#ffffff" BACKGROUND_COLOR="#0033cc" STYLE="bubble" SHAPE_HORIZONTAL_MARGIN="16 px" SHAPE_VERTICAL_MARGIN="10 px" NUMBERED="false" FORMAT="STANDARD_FORMAT" TEXT_ALIGN="CENTER" MAX_WIDTH="10 cm" MIN_WIDTH="0 cm" BORDER_WIDTH_LIKE_EDGE="false" BORDER_WIDTH="1.9 px" BORDER_COLOR_LIKE_EDGE="true" BORDER_COLOR="#2c2b29" BORDER_DASH_LIKE_EDGE="true" BORDER_DASH="SOLID" SHAPE_HORIZONTAL_MARGIN_QUANTITY="8 pt" SHAPE_VERTICAL_MARGIN_QUANTITY="5 pt" HGAP_QUANTITY="-1.75 pt" VSHIFT_QUANTITY="-261.74999 pt">
<font NAME="SansSerif" SIZE="16" BOLD="false" STRIKETHROUGH="false" ITALIC="false"/>
<edge STYLE="bezier" COLOR="#93a1a1" WIDTH="3" DASH="SOLID"/>
<node TEXT="безопасность информации" ID="ID_1636130354" CREATED="1684939636907" MODIFIED="1685112199801" ICON_SIZE="12 pt" COLOR="#ffffff" BACKGROUND_COLOR="#0066cc" STYLE="bubble" SHAPE_HORIZONTAL_MARGIN="16 px" SHAPE_VERTICAL_MARGIN="10 px" NUMBERED="false" FORMAT="STANDARD_FORMAT" TEXT_ALIGN="CENTER" MAX_WIDTH="10 cm" MIN_WIDTH="0 cm" BORDER_WIDTH_LIKE_EDGE="false" BORDER_WIDTH="1.9 px" BORDER_COLOR_LIKE_EDGE="true" BORDER_COLOR="#f0f0f0" BORDER_DASH_LIKE_EDGE="true" BORDER_DASH="SOLID" SHAPE_HORIZONTAL_MARGIN_QUANTITY="8 pt" SHAPE_VERTICAL_MARGIN_QUANTITY="5 pt">
<font NAME="SansSerif" SIZE="12" BOLD="false" STRIKETHROUGH="false" ITALIC="false"/>
<edge STYLE="bezier" COLOR="#93a1a1" WIDTH="3" DASH="SOLID"/>
</node>
<node TEXT="безопасное программное обеспечение" ID="ID_1609406737" CREATED="1684939636907" MODIFIED="1685112214839" ICON_SIZE="12 pt" COLOR="#ffffff" BACKGROUND_COLOR="#0066cc" STYLE="bubble" SHAPE_HORIZONTAL_MARGIN="16 px" SHAPE_VERTICAL_MARGIN="10 px" NUMBERED="false" FORMAT="STANDARD_FORMAT" TEXT_ALIGN="CENTER" MAX_WIDTH="10 cm" MIN_WIDTH="0 cm" BORDER_WIDTH_LIKE_EDGE="false" BORDER_WIDTH="1.9 px" BORDER_COLOR_LIKE_EDGE="true" BORDER_COLOR="#f0f0f0" BORDER_DASH_LIKE_EDGE="true" BORDER_DASH="SOLID" SHAPE_HORIZONTAL_MARGIN_QUANTITY="8 pt" SHAPE_VERTICAL_MARGIN_QUANTITY="5 pt">
<font NAME="SansSerif" SIZE="12" BOLD="false" STRIKETHROUGH="false" ITALIC="false"/>
<edge STYLE="bezier" COLOR="#93a1a1" WIDTH="3" DASH="SOLID"/>
</node>
<node TEXT="динамический анализ кода программы" ID="ID_44118414" CREATED="1684939636907" MODIFIED="1685112229752" ICON_SIZE="12 pt" COLOR="#ffffff" BACKGROUND_COLOR="#0066cc" STYLE="bubble" SHAPE_HORIZONTAL_MARGIN="16 px" SHAPE_VERTICAL_MARGIN="10 px" NUMBERED="false" FORMAT="STANDARD_FORMAT" TEXT_ALIGN="CENTER" MAX_WIDTH="10 cm" MIN_WIDTH="0 cm" BORDER_WIDTH_LIKE_EDGE="false" BORDER_WIDTH="1.9 px" BORDER_COLOR_LIKE_EDGE="true" BORDER_COLOR="#f0f0f0" BORDER_DASH_LIKE_EDGE="true" BORDER_DASH="SOLID" SHAPE_HORIZONTAL_MARGIN_QUANTITY="8 pt" SHAPE_VERTICAL_MARGIN_QUANTITY="5 pt">
<font NAME="SansSerif" SIZE="12" BOLD="false" STRIKETHROUGH="false" ITALIC="false"/>
<edge STYLE="bezier" COLOR="#93a1a1" WIDTH="3" DASH="SOLID"/>
</node>
<node TEXT="документация разработчика программного обеспечение" ID="ID_5314558" CREATED="1684939636907" MODIFIED="1685112240011" ICON_SIZE="12 pt" COLOR="#ffffff" BACKGROUND_COLOR="#0066cc" STYLE="bubble" SHAPE_HORIZONTAL_MARGIN="16 px" SHAPE_VERTICAL_MARGIN="10 px" NUMBERED="false" FORMAT="STANDARD_FORMAT" TEXT_ALIGN="CENTER" MAX_WIDTH="10 cm" MIN_WIDTH="0 cm" BORDER_WIDTH_LIKE_EDGE="false" BORDER_WIDTH="1.9 px" BORDER_COLOR_LIKE_EDGE="true" BORDER_COLOR="#f0f0f0" BORDER_DASH_LIKE_EDGE="true" BORDER_DASH="SOLID" SHAPE_HORIZONTAL_MARGIN_QUANTITY="8 pt" SHAPE_VERTICAL_MARGIN_QUANTITY="5 pt">
<font NAME="SansSerif" SIZE="12" BOLD="false" STRIKETHROUGH="false" ITALIC="false"/>
<edge STYLE="bezier" COLOR="#93a1a1" WIDTH="3" DASH="SOLID"/>
</node>
<node TEXT="инструментальное средство" ID="ID_1361388802" CREATED="1684939636907" MODIFIED="1685112250925" ICON_SIZE="12 pt" COLOR="#ffffff" BACKGROUND_COLOR="#0066cc" STYLE="bubble" SHAPE_HORIZONTAL_MARGIN="16 px" SHAPE_VERTICAL_MARGIN="10 px" NUMBERED="false" FORMAT="STANDARD_FORMAT" TEXT_ALIGN="CENTER" MAX_WIDTH="10 cm" MIN_WIDTH="0 cm" BORDER_WIDTH_LIKE_EDGE="false" BORDER_WIDTH="1.9 px" BORDER_COLOR_LIKE_EDGE="true" BORDER_COLOR="#f0f0f0" BORDER_DASH_LIKE_EDGE="true" BORDER_DASH="SOLID" SHAPE_HORIZONTAL_MARGIN_QUANTITY="8 pt" SHAPE_VERTICAL_MARGIN_QUANTITY="5 pt">
<font NAME="SansSerif" SIZE="12" BOLD="false" STRIKETHROUGH="false" ITALIC="false"/>
<edge STYLE="bezier" COLOR="#93a1a1" WIDTH="3" DASH="SOLID"/>
</node>
<node TEXT="компьютерная атака" ID="ID_1183764954" CREATED="1684939636907" MODIFIED="1685112256937" ICON_SIZE="12 pt" COLOR="#ffffff" BACKGROUND_COLOR="#0066cc" STYLE="bubble" SHAPE_HORIZONTAL_MARGIN="16 px" SHAPE_VERTICAL_MARGIN="10 px" NUMBERED="false" FORMAT="STANDARD_FORMAT" TEXT_ALIGN="CENTER" MAX_WIDTH="10 cm" MIN_WIDTH="0 cm" BORDER_WIDTH_LIKE_EDGE="false" BORDER_WIDTH="1.9 px" BORDER_COLOR_LIKE_EDGE="true" BORDER_COLOR="#f0f0f0" BORDER_DASH_LIKE_EDGE="true" BORDER_DASH="SOLID" SHAPE_HORIZONTAL_MARGIN_QUANTITY="8 pt" SHAPE_VERTICAL_MARGIN_QUANTITY="5 pt">
<font NAME="SansSerif" SIZE="12" BOLD="false" STRIKETHROUGH="false" ITALIC="false"/>
<edge STYLE="bezier" COLOR="#93a1a1" WIDTH="3" DASH="SOLID"/>
</node>
<node TEXT="недостаток программы" ID="ID_1805954084" CREATED="1684939636907" MODIFIED="1685112262525" ICON_SIZE="12 pt" COLOR="#ffffff" BACKGROUND_COLOR="#0066cc" STYLE="bubble" SHAPE_HORIZONTAL_MARGIN="16 px" SHAPE_VERTICAL_MARGIN="10 px" NUMBERED="false" FORMAT="STANDARD_FORMAT" TEXT_ALIGN="CENTER" MAX_WIDTH="10 cm" MIN_WIDTH="0 cm" BORDER_WIDTH_LIKE_EDGE="false" BORDER_WIDTH="1.9 px" BORDER_COLOR_LIKE_EDGE="true" BORDER_COLOR="#f0f0f0" BORDER_DASH_LIKE_EDGE="true" BORDER_DASH="SOLID" SHAPE_HORIZONTAL_MARGIN_QUANTITY="8 pt" SHAPE_VERTICAL_MARGIN_QUANTITY="5 pt">
<font NAME="SansSerif" SIZE="12" BOLD="false" STRIKETHROUGH="false" ITALIC="false"/>
<edge STYLE="bezier" COLOR="#93a1a1" WIDTH="3" DASH="SOLID"/>
</node>
<node TEXT="объект среды разработки программного обеспечения" ID="ID_487365833" CREATED="1684939636907" MODIFIED="1685112273099" ICON_SIZE="12 pt" COLOR="#ffffff" BACKGROUND_COLOR="#0066cc" STYLE="bubble" SHAPE_HORIZONTAL_MARGIN="16 px" SHAPE_VERTICAL_MARGIN="10 px" NUMBERED="false" FORMAT="STANDARD_FORMAT" TEXT_ALIGN="CENTER" MAX_WIDTH="10 cm" MIN_WIDTH="0 cm" BORDER_WIDTH_LIKE_EDGE="false" BORDER_WIDTH="1.9 px" BORDER_COLOR_LIKE_EDGE="true" BORDER_COLOR="#f0f0f0" BORDER_DASH_LIKE_EDGE="true" BORDER_DASH="SOLID" SHAPE_HORIZONTAL_MARGIN_QUANTITY="8 pt" SHAPE_VERTICAL_MARGIN_QUANTITY="5 pt">
<font NAME="SansSerif" SIZE="12" BOLD="false" STRIKETHROUGH="false" ITALIC="false"/>
<edge STYLE="bezier" COLOR="#93a1a1" WIDTH="3" DASH="SOLID"/>
</node>
<node TEXT="пользователь (программного обеспечения)" ID="ID_1870622389" CREATED="1684939636907" MODIFIED="1685112284225" ICON_SIZE="12 pt" COLOR="#ffffff" BACKGROUND_COLOR="#0066cc" STYLE="bubble" SHAPE_HORIZONTAL_MARGIN="16 px" SHAPE_VERTICAL_MARGIN="10 px" NUMBERED="false" FORMAT="STANDARD_FORMAT" TEXT_ALIGN="CENTER" MAX_WIDTH="10 cm" MIN_WIDTH="0 cm" BORDER_WIDTH_LIKE_EDGE="false" BORDER_WIDTH="1.9 px" BORDER_COLOR_LIKE_EDGE="true" BORDER_COLOR="#f0f0f0" BORDER_DASH_LIKE_EDGE="true" BORDER_DASH="SOLID" SHAPE_HORIZONTAL_MARGIN_QUANTITY="8 pt" SHAPE_VERTICAL_MARGIN_QUANTITY="5 pt">
<font NAME="SansSerif" SIZE="12" BOLD="false" STRIKETHROUGH="false" ITALIC="false"/>
<edge STYLE="bezier" COLOR="#93a1a1" WIDTH="3" DASH="SOLID"/>
</node>
<node TEXT="программа" ID="ID_222088677" CREATED="1684939636907" MODIFIED="1685112287401" ICON_SIZE="12 pt" COLOR="#ffffff" BACKGROUND_COLOR="#0066cc" STYLE="bubble" SHAPE_HORIZONTAL_MARGIN="16 px" SHAPE_VERTICAL_MARGIN="10 px" NUMBERED="false" FORMAT="STANDARD_FORMAT" TEXT_ALIGN="CENTER" MAX_WIDTH="10 cm" MIN_WIDTH="0 cm" BORDER_WIDTH_LIKE_EDGE="false" BORDER_WIDTH="1.9 px" BORDER_COLOR_LIKE_EDGE="true" BORDER_COLOR="#f0f0f0" BORDER_DASH_LIKE_EDGE="true" BORDER_DASH="SOLID" SHAPE_HORIZONTAL_MARGIN_QUANTITY="8 pt" SHAPE_VERTICAL_MARGIN_QUANTITY="5 pt">
<font NAME="SansSerif" SIZE="12" BOLD="false" STRIKETHROUGH="false" ITALIC="false"/>
<edge STYLE="bezier" COLOR="#93a1a1" WIDTH="3" DASH="SOLID"/>
</node>
<node TEXT="программное обеспечение" ID="ID_1814625535" CREATED="1684939636907" MODIFIED="1685112291201" ICON_SIZE="12 pt" COLOR="#ffffff" BACKGROUND_COLOR="#0066cc" STYLE="bubble" SHAPE_HORIZONTAL_MARGIN="16 px" SHAPE_VERTICAL_MARGIN="10 px" NUMBERED="false" FORMAT="STANDARD_FORMAT" TEXT_ALIGN="CENTER" MAX_WIDTH="10 cm" MIN_WIDTH="0 cm" BORDER_WIDTH_LIKE_EDGE="false" BORDER_WIDTH="1.9 px" BORDER_COLOR_LIKE_EDGE="true" BORDER_COLOR="#f0f0f0" BORDER_DASH_LIKE_EDGE="true" BORDER_DASH="SOLID" SHAPE_HORIZONTAL_MARGIN_QUANTITY="8 pt" SHAPE_VERTICAL_MARGIN_QUANTITY="5 pt">
<font NAME="SansSerif" SIZE="12" BOLD="false" STRIKETHROUGH="false" ITALIC="false"/>
<edge STYLE="bezier" COLOR="#93a1a1" WIDTH="3" DASH="SOLID"/>
</node>
<node TEXT="сетевая атака" ID="ID_320939938" CREATED="1684939636907" MODIFIED="1685112296027" ICON_SIZE="12 pt" COLOR="#ffffff" BACKGROUND_COLOR="#0066cc" STYLE="bubble" SHAPE_HORIZONTAL_MARGIN="16 px" SHAPE_VERTICAL_MARGIN="10 px" NUMBERED="false" FORMAT="STANDARD_FORMAT" TEXT_ALIGN="CENTER" MAX_WIDTH="10 cm" MIN_WIDTH="0 cm" BORDER_WIDTH_LIKE_EDGE="false" BORDER_WIDTH="1.9 px" BORDER_COLOR_LIKE_EDGE="true" BORDER_COLOR="#f0f0f0" BORDER_DASH_LIKE_EDGE="true" BORDER_DASH="SOLID" SHAPE_HORIZONTAL_MARGIN_QUANTITY="8 pt" SHAPE_VERTICAL_MARGIN_QUANTITY="5 pt">
<font NAME="SansSerif" SIZE="12" BOLD="false" STRIKETHROUGH="false" ITALIC="false"/>
<edge STYLE="bezier" COLOR="#93a1a1" WIDTH="3" DASH="SOLID"/>
</node>
<node TEXT="система управления конфигурацией программного обеспечения" ID="ID_1571514888" CREATED="1684939636907" MODIFIED="1685112306689" ICON_SIZE="12 pt" COLOR="#ffffff" BACKGROUND_COLOR="#0066cc" STYLE="bubble" SHAPE_HORIZONTAL_MARGIN="16 px" SHAPE_VERTICAL_MARGIN="10 px" NUMBERED="false" FORMAT="STANDARD_FORMAT" TEXT_ALIGN="CENTER" MAX_WIDTH="10 cm" MIN_WIDTH="0 cm" BORDER_WIDTH_LIKE_EDGE="false" BORDER_WIDTH="1.9 px" BORDER_COLOR_LIKE_EDGE="true" BORDER_COLOR="#f0f0f0" BORDER_DASH_LIKE_EDGE="true" BORDER_DASH="SOLID" SHAPE_HORIZONTAL_MARGIN_QUANTITY="8 pt" SHAPE_VERTICAL_MARGIN_QUANTITY="5 pt">
<font NAME="SansSerif" SIZE="12" BOLD="false" STRIKETHROUGH="false" ITALIC="false"/>
<edge STYLE="bezier" COLOR="#93a1a1" WIDTH="3" DASH="SOLID"/>
</node>
<node TEXT="среда разработки программного обеспечения" ID="ID_373591726" CREATED="1684939636907" MODIFIED="1685112313388" ICON_SIZE="12 pt" COLOR="#ffffff" BACKGROUND_COLOR="#0066cc" STYLE="bubble" SHAPE_HORIZONTAL_MARGIN="16 px" SHAPE_VERTICAL_MARGIN="10 px" NUMBERED="false" FORMAT="STANDARD_FORMAT" TEXT_ALIGN="CENTER" MAX_WIDTH="10 cm" MIN_WIDTH="0 cm" BORDER_WIDTH_LIKE_EDGE="false" BORDER_WIDTH="1.9 px" BORDER_COLOR_LIKE_EDGE="true" BORDER_COLOR="#f0f0f0" BORDER_DASH_LIKE_EDGE="true" BORDER_DASH="SOLID" SHAPE_HORIZONTAL_MARGIN_QUANTITY="8 pt" SHAPE_VERTICAL_MARGIN_QUANTITY="5 pt">
<font NAME="SansSerif" SIZE="12" BOLD="false" STRIKETHROUGH="false" ITALIC="false"/>
<edge STYLE="bezier" COLOR="#93a1a1" WIDTH="3" DASH="SOLID"/>
</node>
<node TEXT="статический анализ исходного кода программы" ID="ID_83654379" CREATED="1684939636907" MODIFIED="1685112322528" ICON_SIZE="12 pt" COLOR="#ffffff" BACKGROUND_COLOR="#0066cc" STYLE="bubble" SHAPE_HORIZONTAL_MARGIN="16 px" SHAPE_VERTICAL_MARGIN="10 px" NUMBERED="false" FORMAT="STANDARD_FORMAT" TEXT_ALIGN="CENTER" MAX_WIDTH="10 cm" MIN_WIDTH="0 cm" BORDER_WIDTH_LIKE_EDGE="false" BORDER_WIDTH="1.9 px" BORDER_COLOR_LIKE_EDGE="true" BORDER_COLOR="#f0f0f0" BORDER_DASH_LIKE_EDGE="true" BORDER_DASH="SOLID" SHAPE_HORIZONTAL_MARGIN_QUANTITY="8 pt" SHAPE_VERTICAL_MARGIN_QUANTITY="5 pt">
<font NAME="SansSerif" SIZE="12" BOLD="false" STRIKETHROUGH="false" ITALIC="false"/>
<edge STYLE="bezier" COLOR="#93a1a1" WIDTH="3" DASH="SOLID"/>
</node>
<node TEXT="тестирование на проникновение" ID="ID_1948053518" CREATED="1684939636907" MODIFIED="1685112328326" ICON_SIZE="12 pt" COLOR="#ffffff" BACKGROUND_COLOR="#0066cc" STYLE="bubble" SHAPE_HORIZONTAL_MARGIN="16 px" SHAPE_VERTICAL_MARGIN="10 px" NUMBERED="false" FORMAT="STANDARD_FORMAT" TEXT_ALIGN="CENTER" MAX_WIDTH="10 cm" MIN_WIDTH="0 cm" BORDER_WIDTH_LIKE_EDGE="false" BORDER_WIDTH="1.9 px" BORDER_COLOR_LIKE_EDGE="true" BORDER_COLOR="#f0f0f0" BORDER_DASH_LIKE_EDGE="true" BORDER_DASH="SOLID" SHAPE_HORIZONTAL_MARGIN_QUANTITY="8 pt" SHAPE_VERTICAL_MARGIN_QUANTITY="5 pt">
<font NAME="SansSerif" SIZE="12" BOLD="false" STRIKETHROUGH="false" ITALIC="false"/>
<edge STYLE="bezier" COLOR="#93a1a1" WIDTH="3" DASH="SOLID"/>
</node>
<node TEXT="угроза (безопасности информации)" ID="ID_1586224334" CREATED="1684939636907" MODIFIED="1685112340550" ICON_SIZE="12 pt" COLOR="#ffffff" BACKGROUND_COLOR="#0066cc" STYLE="bubble" SHAPE_HORIZONTAL_MARGIN="16 px" SHAPE_VERTICAL_MARGIN="10 px" NUMBERED="false" FORMAT="STANDARD_FORMAT" TEXT_ALIGN="CENTER" MAX_WIDTH="10 cm" MIN_WIDTH="0 cm" BORDER_WIDTH_LIKE_EDGE="false" BORDER_WIDTH="1.9 px" BORDER_COLOR_LIKE_EDGE="true" BORDER_COLOR="#f0f0f0" BORDER_DASH_LIKE_EDGE="true" BORDER_DASH="SOLID" SHAPE_HORIZONTAL_MARGIN_QUANTITY="8 pt" SHAPE_VERTICAL_MARGIN_QUANTITY="5 pt">
<font NAME="SansSerif" SIZE="12" BOLD="false" STRIKETHROUGH="false" ITALIC="false"/>
<edge STYLE="bezier" COLOR="#93a1a1" WIDTH="3" DASH="SOLID"/>
</node>
<node TEXT="управление конфигурацией программного обеспечения" ID="ID_696634078" CREATED="1684939636907" MODIFIED="1685112350637" ICON_SIZE="12 pt" COLOR="#ffffff" BACKGROUND_COLOR="#0066cc" STYLE="bubble" SHAPE_HORIZONTAL_MARGIN="16 px" SHAPE_VERTICAL_MARGIN="10 px" NUMBERED="false" FORMAT="STANDARD_FORMAT" TEXT_ALIGN="CENTER" MAX_WIDTH="10 cm" MIN_WIDTH="0 cm" BORDER_WIDTH_LIKE_EDGE="false" BORDER_WIDTH="1.9 px" BORDER_COLOR_LIKE_EDGE="true" BORDER_COLOR="#f0f0f0" BORDER_DASH_LIKE_EDGE="true" BORDER_DASH="SOLID" SHAPE_HORIZONTAL_MARGIN_QUANTITY="8 pt" SHAPE_VERTICAL_MARGIN_QUANTITY="5 pt">
<font NAME="SansSerif" SIZE="12" BOLD="false" STRIKETHROUGH="false" ITALIC="false"/>
<edge STYLE="bezier" COLOR="#93a1a1" WIDTH="3" DASH="SOLID"/>
</node>
<node TEXT="уязвимость программы" ID="ID_1042366986" CREATED="1684939636907" MODIFIED="1685112356337" ICON_SIZE="12 pt" COLOR="#ffffff" BACKGROUND_COLOR="#0066cc" STYLE="bubble" SHAPE_HORIZONTAL_MARGIN="16 px" SHAPE_VERTICAL_MARGIN="10 px" NUMBERED="false" FORMAT="STANDARD_FORMAT" TEXT_ALIGN="CENTER" MAX_WIDTH="10 cm" MIN_WIDTH="0 cm" BORDER_WIDTH_LIKE_EDGE="false" BORDER_WIDTH="1.9 px" BORDER_COLOR_LIKE_EDGE="true" BORDER_COLOR="#f0f0f0" BORDER_DASH_LIKE_EDGE="true" BORDER_DASH="SOLID" SHAPE_HORIZONTAL_MARGIN_QUANTITY="8 pt" SHAPE_VERTICAL_MARGIN_QUANTITY="5 pt">
<font NAME="SansSerif" SIZE="12" BOLD="false" STRIKETHROUGH="false" ITALIC="false"/>
<edge STYLE="bezier" COLOR="#93a1a1" WIDTH="3" DASH="SOLID"/>
</node>
<node TEXT="финциональное тестирование программы" ID="ID_1386885303" CREATED="1684939636907" MODIFIED="1685112368689" ICON_SIZE="12 pt" COLOR="#ffffff" BACKGROUND_COLOR="#0066cc" STYLE="bubble" SHAPE_HORIZONTAL_MARGIN="16 px" SHAPE_VERTICAL_MARGIN="10 px" NUMBERED="false" FORMAT="STANDARD_FORMAT" TEXT_ALIGN="CENTER" MAX_WIDTH="10 cm" MIN_WIDTH="0 cm" BORDER_WIDTH_LIKE_EDGE="false" BORDER_WIDTH="1.9 px" BORDER_COLOR_LIKE_EDGE="true" BORDER_COLOR="#f0f0f0" BORDER_DASH_LIKE_EDGE="true" BORDER_DASH="SOLID" SHAPE_HORIZONTAL_MARGIN_QUANTITY="8 pt" SHAPE_VERTICAL_MARGIN_QUANTITY="5 pt">
<font NAME="SansSerif" SIZE="12" BOLD="false" STRIKETHROUGH="false" ITALIC="false"/>
<edge STYLE="bezier" COLOR="#93a1a1" WIDTH="3" DASH="SOLID"/>
</node>
<node TEXT="фаззинг-тестирование программы" ID="ID_558320437" CREATED="1684939636907" MODIFIED="1685112380763" ICON_SIZE="12 pt" COLOR="#ffffff" BACKGROUND_COLOR="#0066cc" STYLE="bubble" SHAPE_HORIZONTAL_MARGIN="16 px" SHAPE_VERTICAL_MARGIN="10 px" NUMBERED="false" FORMAT="STANDARD_FORMAT" TEXT_ALIGN="CENTER" MAX_WIDTH="10 cm" MIN_WIDTH="0 cm" BORDER_WIDTH_LIKE_EDGE="false" BORDER_WIDTH="1.9 px" BORDER_COLOR_LIKE_EDGE="true" BORDER_COLOR="#f0f0f0" BORDER_DASH_LIKE_EDGE="true" BORDER_DASH="SOLID" SHAPE_HORIZONTAL_MARGIN_QUANTITY="8 pt" SHAPE_VERTICAL_MARGIN_QUANTITY="5 pt">
<font NAME="SansSerif" SIZE="12" BOLD="false" STRIKETHROUGH="false" ITALIC="false"/>
<edge STYLE="bezier" COLOR="#93a1a1" WIDTH="3" DASH="SOLID"/>
</node>
<node TEXT="экспертиза исходного кода программы" ID="ID_163115361" CREATED="1684939636907" MODIFIED="1685112389201" ICON_SIZE="12 pt" COLOR="#ffffff" BACKGROUND_COLOR="#0066cc" STYLE="bubble" SHAPE_HORIZONTAL_MARGIN="16 px" SHAPE_VERTICAL_MARGIN="10 px" NUMBERED="false" FORMAT="STANDARD_FORMAT" TEXT_ALIGN="CENTER" MAX_WIDTH="10 cm" MIN_WIDTH="0 cm" BORDER_WIDTH_LIKE_EDGE="false" BORDER_WIDTH="1.9 px" BORDER_COLOR_LIKE_EDGE="true" BORDER_COLOR="#f0f0f0" BORDER_DASH_LIKE_EDGE="true" BORDER_DASH="SOLID" SHAPE_HORIZONTAL_MARGIN_QUANTITY="8 pt" SHAPE_VERTICAL_MARGIN_QUANTITY="5 pt">
<font NAME="SansSerif" SIZE="12" BOLD="false" STRIKETHROUGH="false" ITALIC="false"/>
<edge STYLE="bezier" COLOR="#93a1a1" WIDTH="3" DASH="SOLID"/>
</node>
<node TEXT="электронный документ" ID="ID_73271780" CREATED="1684939636907" MODIFIED="1685112394063" ICON_SIZE="12 pt" COLOR="#ffffff" BACKGROUND_COLOR="#0066cc" STYLE="bubble" SHAPE_HORIZONTAL_MARGIN="16 px" SHAPE_VERTICAL_MARGIN="10 px" NUMBERED="false" FORMAT="STANDARD_FORMAT" TEXT_ALIGN="CENTER" MAX_WIDTH="10 cm" MIN_WIDTH="0 cm" BORDER_WIDTH_LIKE_EDGE="false" BORDER_WIDTH="1.9 px" BORDER_COLOR_LIKE_EDGE="true" BORDER_COLOR="#f0f0f0" BORDER_DASH_LIKE_EDGE="true" BORDER_DASH="SOLID" SHAPE_HORIZONTAL_MARGIN_QUANTITY="8 pt" SHAPE_VERTICAL_MARGIN_QUANTITY="5 pt">
<font NAME="SansSerif" SIZE="12" BOLD="false" STRIKETHROUGH="false" ITALIC="false"/>
<edge STYLE="bezier" COLOR="#93a1a1" WIDTH="3" DASH="SOLID"/>
</node>
<node TEXT="элемент конфигурации" ID="ID_707096852" CREATED="1684939636907" MODIFIED="1685112400725" ICON_SIZE="12 pt" COLOR="#ffffff" BACKGROUND_COLOR="#0066cc" STYLE="bubble" SHAPE_HORIZONTAL_MARGIN="16 px" SHAPE_VERTICAL_MARGIN="10 px" NUMBERED="false" FORMAT="STANDARD_FORMAT" TEXT_ALIGN="CENTER" MAX_WIDTH="10 cm" MIN_WIDTH="0 cm" BORDER_WIDTH_LIKE_EDGE="false" BORDER_WIDTH="1.9 px" BORDER_COLOR_LIKE_EDGE="true" BORDER_COLOR="#f0f0f0" BORDER_DASH_LIKE_EDGE="true" BORDER_DASH="SOLID" SHAPE_HORIZONTAL_MARGIN_QUANTITY="8 pt" SHAPE_VERTICAL_MARGIN_QUANTITY="5 pt">
<font NAME="SansSerif" SIZE="12" BOLD="false" STRIKETHROUGH="false" ITALIC="false"/>
<edge STYLE="bezier" COLOR="#93a1a1" WIDTH="3" DASH="SOLID"/>
</node>
</node>
<node TEXT="Общие положения" POSITION="top_or_left" ID="ID_1837544048" CREATED="1684937145558" MODIFIED="1685112639863" ICON_SIZE="12 pt" COLOR="#ffffff" BACKGROUND_COLOR="#0033cc" STYLE="bubble" SHAPE_HORIZONTAL_MARGIN="16 px" SHAPE_VERTICAL_MARGIN="10 px" NUMBERED="false" FORMAT="STANDARD_FORMAT" TEXT_ALIGN="CENTER" MAX_WIDTH="10 cm" MIN_WIDTH="0 cm" BORDER_WIDTH_LIKE_EDGE="false" BORDER_WIDTH="1.9 px" BORDER_COLOR_LIKE_EDGE="true" BORDER_COLOR="#2c2b29" BORDER_DASH_LIKE_EDGE="true" BORDER_DASH="SOLID" HGAP_QUANTITY="-90.00001 pt" VSHIFT_QUANTITY="-119.49996 pt" SHAPE_HORIZONTAL_MARGIN_QUANTITY="8 pt" SHAPE_VERTICAL_MARGIN_QUANTITY="5 pt">
<font NAME="SansSerif" SIZE="16" BOLD="false" STRIKETHROUGH="false" ITALIC="false"/>
<edge STYLE="bezier" COLOR="#93a1a1" WIDTH="3" DASH="SOLID"/>
</node>
</node>
</map>
