---
title: "Применение средств и методов OSINT"
author: Георгий Жидков
format: 
    md:
        output-file: README.md
engine: knitr
---

# Применение средств и методов OSINT

## Цель работы

1.  Освоить базовые подходы процессов OSINT
2.  Освоить современные инструменты поиска и сбора информации
3.  Освоить инструменты совместной работы в ходе аналитической деятельности

## Задание

1.  Собрать информацию о компании Информзащита
2.  Собрать информацию об основных специализированных технологиях, применяемых в средствах защиты информации.
3.  Собрать информацию о публичных сотрудниках, ведущих профильные технологические блоги, профили в социальных сетях и т.д.
4.  Сформировать представление о рынке отечественных решений ИБ

## Ход работы

### 1. Полное наименование компании

АКЦИОНЕРНОЕ ОБЩЕСТВО НАУЧНО-ИНЖЕНЕРНОЕ ПРЕДПРИЯТИЕ "ИНФОРМЗАЩИТА"
[Источник](https://sbis.ru/contragents/7702148410/770201001)

### 2. Структура компании

В публичных источниках информация о структуре компании отсутствует.
Есть только информация о группе компаний с их официального сайта:
На сегодняшний день в группу компаний «Информзащита» входит пять компаний: НИП «Информзащита», «Информзащита-Сервис», «Национальный аттестационный центр», Учебный центр «Информзащита», Spacebit. Компания «Код Безопасности» ранее входила в ГК «Информзащита».
[Источник](https://www.infosec.ru/about/company-group/)

### 3. Основные направления деятельности компании

#### Услуги

- Защита инфраструктуры
- Проектирование и внедрение
- Аудит ИБ и безопасность бизнес-процессов
- Управление безопасностью
- Защита информации
- Анализ защищенности
- Соответствие требованиям
- Промышленная безопасность
- Защита от мошенничества
- Сопровождение и поддержка решений по ИБ

[Источник](https://www.infosec.ru/)

#### Производимые продукты, основные сферы их применения, их достоинства

Сертифицированные средства защиты информации компании «Информзащита»:

- Программно-аппаратный комплекс «Соболь»;
- Аппаратно-программный комплекс шифрования «Континент»;
- Cистема защиты информации (СЗИ) «Континент-АП»;
- СЗИ Secret Net 5.0 (автономный и сетевой варианты);
- СЗИ Security Studio;
- Cистема автоматизированного управления доступом КУБ и др.

[Источник](https://www.infosec.ru/)

#### Используемые технологии, языки программирования

Информация в открытых источниках отсутствует.

### 4. Основные клиенты компаниии

- Альфа-Банк
- Газпром
- Концерн ПВО "Алмаз-Антей"
- Ростех
- X5 Retail Group
- ОАО "РЖД"
- Банк "Ренессанс Кредит"
- ЛУКОЙЛ
- Центральный банк Российской Федерации
- Федеральное казначейство
- Альфа Страхование
- МЧС России

[Источник](https://www.infosec.ru/projects/)

### 5. Основные веб-сайты компании и её продуктов

Основной веб-сайт - https://www.infosec.ru/
Ютуб-канал - https://www.youtube.com/@infosec_ru
Страница ВК - https://vk.com/infosec

### 6. Публичные сотрудники компании, активные участники ИТ и ИБ-сообщества, участники профильных конференций, Twitter, Mastodon, Телеграмм-каналов и т.д.

Иван Мелехин - Руководитель центра мониторинга и кибербезопасности компании
[Источник](https://youtu.be/PB9oTLY8B6c)

### 7. Уникальные достижения, ключевые продукты компании

Право исполнять функции центра ГосСОПКА для госорганов, юрлиц и ИП России
ФСБ России и компания «Информзащита», системный интегратор в сфере информационной безопасности, 18 января 2019 года объявили о подписании соглашения о взаимодействии в области обнаружения, предупреждения и ликвидации компьютерных атак в рамках ГосСОПКА.

[Источник](https://www.tadviser.ru/index.php/%D0%9A%D0%BE%D0%BC%D0%BF%D0%B0%D0%BD%D0%B8%D1%8F:%D0%98%D0%BD%D1%84%D0%BE%D1%80%D0%BC%D0%B7%D0%B0%D1%89%D0%B8%D1%82%D0%B0)

Ведущий российский ИБ-интегратор «Информзащита» подтвердил полное соответствие применяемых в «Аэроэкспресс» политик информационной безопасности требованиям стандарта PCI DSS v 3.2.1.

[Источник](https://www.infosec.ru/projects/promyshlennost-i-transport/proekt-po-otsenke-urovnya-sootvetstviya-kompanii-aeroekspress-trebovaniyam-standarta-pci-dss-v-3-2-1/)

Подтверждение соответствия Visa QIWI Wallet требованиям стандарта PCI DSS

[Источник](https://www.infosec.ru/projects/finansy-i-strakhovanie/podtverzhdenie-sootvetstviya-visa-qiwi-wallet-trebovaniyam-standarta-pci-dss/)

Подтверждение соответствия Главного процессингового центра Сбербанка России требованиям стандарта PCI DSS

[Источник](https://www.infosec.ru/projects/finansy-i-strakhovanie/podtverzhdenie-sootvetstviya-glavnogo-protsessingovogo-tsentra-sberbanka-rossii-trebovaniyam-standarta-pci-dss/)

## Выводы

В результате выполнения практической работы была найдена и проанализирована информация о компании Информзащита с применением средств и методов OSINT